### ISSUE TITLE
פקד עוצמת ההקלטה לא מתפקד באופן לינארי.

### ISSUE THREAD

**Issue by ariel1974** [ariel1974/mymentor#1]
פקד עוצמת ההקלטה לא מתפקד באופן לינארי. ז"א שאם הוא במינימום הוא לא מקליט, אבל בכל שאר המצבים עוצמת ההקלטה לא משתנה לפיו.

**Comment by natan1957** [comment]
עדיין לא מתפקד למרות שסומן כ - טופל

**Comment by ariel1974** [comment]
זה עדיין פתוח ?
