### ISSUE TITLE
delete ראשון

### ISSUE THREAD

**Issue by natan1957** [ariel1974/mymentor#100]
לאחר טעינת קובץ מתוזמן, בכניסה לחוצץ הקלטה או תזמון, אם לוחצים על מקש דל (מחיקה) מתבצעת פעולה לא ברורה כולל רענון של חלון הסאונד. לא ברור מה זה עושה, בכל מרקה זה נותן תחושה שקרה משהו ולא ברור מה...
רצוי למנוע את זה.

**Comment by natan1957** [comment]
יותר מזה... אם עוברים ממסך הקלטה או תזמון לטקסט, ומנסים לבצע דליט, בפעם הראשונה זה לא עובד אלא רק בשניה.

דרך אגב, תקלה מס' 100. סיבה לחגיגה...

**Comment by natan1957** [comment]
כשעוברים ממסך הקלטה או תזמון לטקסט, מקש דליט לא פועל

**Comment by ariel1974** [comment]
טופל בגרסה שללחתי אתמול

**Comment by natan1957** [comment]
זה לא עובד.
תנסה עם הטקסט ששלחתי קודם.
לא מאפשר דל מהרגע הראשון

**Comment by natan1957** [comment]
נשבע לך לא עובד, בחיא עיוני לא עובד... (תנסה עם המנגינה...) חחח

**Comment by ariel1974** [comment]
חחח
תן לי תסריט מדויק מה לעשות שאיירט את הבאג

**Comment by natan1957** [comment]
להלן תסריט מדויק. אל תשנה כלום.
העתק את הקטע שצירפתי מטה לקליפ-בורד
פתח את הסטודיו.
העתק את הטקסט מהקלפ-בורד לסטודיו.
הצב את הסמן לפני האות ס של הר סיני (מופיע בהתחלה של הקטע) חחח 
הקש דל
הקש שוב דל.
לך למחסן והבא פטיש...

 כ וַיֵּ֧רֶד יְהוָ֛ה עַל־הַ֥ר סִינַ֖י אֶל־רֹ֣אשׁ הָהָ֑ר וַיִּקְרָ֨א יְהוָ֧ה לְמֹשֶׁ֛ה אֶל־רֹ֥אשׁ הָהָ֖ר וַיַּ֥עַל מֹשֶֽׁה׃ כא וַיֹּ֤אמֶר יְהוָה֙ אֶל־מֹשֶׁ֔ה רֵ֖ד הָעֵ֣ד בָּעָ֑ם פֶּן־יֶֽהֶרְס֤וּ אֶל־יְהוָה֙ לִרְא֔וֹת וְנָפַ֥ל מִמֶּ֖נּוּ רָֽב׃ כבוְגַ֧ם הַכֹּֽהֲנִ֛ים הַנִּגָּשִׁ֥ים אֶל־יְהוָ֖ה יִתְקַדָּ֑שׁוּ פֶּן־יִפְרֹ֥ץ בָּהֶ֖ם יְהוָֽה׃ כג וַיֹּ֤אמֶר מֹשֶׁה֙ אֶל־יְהוָ֔ה לֹֽא־יוּכַ֣ל הָעָ֔ם לַֽעֲלֹ֖ת אֶל־הַ֣ר סִינָ֑י כִּֽי־אַתָּ֞ה הַֽעֵדֹ֤תָה בָּ֨נוּ֙ לֵאמֹ֔ר הַגְבֵּ֥ל אֶת־הָהָ֖ר וְקִדַּשְׁתּֽוֹ׃

**Comment by ariel1974** [comment]
נתן זו ההתנהגות עם טקסט מנוקד. שים לב שהדליט הראשון מוחק את הניקוד והשני מוחק את האות. אין לי מה לתקן כאן, מחזיר את הפטיש למקום

**Comment by natan1957** [comment]
הועבר לסעיף 122
