### ISSUE TITLE
מחיקת עוגנים רבים

### ISSUE THREAD

**Issue by natan1957** [ariel1974/mymentor#101]
מחיקת עוגנים ידנית ע"י גורעת מעברים רלוונטיים.
זה קורה כשמוחקים בודדים ע"י לחיצה על העוגן כשהכפתור הרלוונטי לחוץ.
אבל במחיקת כל העוגנים מסוג מסוים ע"י לחיצה על מינוס, נוצר בלאגן.

**Comment by ariel1974** [comment]
לא מבין

**Comment by natan1957** [comment]
מחיקת עוגנים רבים על ידי לחיצה על הצבע הרלוונטי ואחריו לחיצה על מינוס, לא מתאפשרת.
קופצת הודעה כאילו זו מחיקה ידנית.
יש לאפשר מחיקה מסוג זה ולמחוק עוגנים רלוונטיים.
זה נכון גם במחיקת כל העוגנים דרך התפריט.

**Comment by natan1957** [comment]
לא עובד

**Comment by ariel1974** [comment]
done

**Comment by natan1957** [comment]
הללויה...

נשלח מה-iPhone שלי

ב-May 16, 2014, בשעה 20:02, Ariel Illouz notifications@github.com כתב/ה:

**Comment by natan1957** [comment]
טיפלת גם בשאר העניינים?

נשלח מה-iPhone שלי

ב-May 16, 2014, בשעה 20:02, Ariel Illouz notifications@github.com כתב/ה:

**Comment by natan1957** [comment]
מצב התחלתי
![image](https://cloud.githubusercontent.com/assets/6491631/3002016/eb04aa9c-dd38-11e3-845b-629fe28950e3.png)

אני מוחק את כל העוגנים הירוקים
למה המעבר של העוגן שנשאר זז ?
כאשר אני מוחק אותם אחד אחד זה תקין...
![image](https://cloud.githubusercontent.com/assets/6491631/3002033/3479c4dc-dd39-11e3-99cc-9c3e6779ae7f.png)

**Comment by natan1957** [comment]
במחיקת כל העוגנים ע"י הכפתורים הצבעוניים + כפתור מינוס, יש למחוק גם את המעבר הראשון והאחרון.
כמו במחיקת כל העוגנים דרך התפריט.
הישארות המעבר האחרון גורמת לכך שהוספת עוגן מוסיפה מעבר וזה לא נכון במצב הזה
![image](https://cloud.githubusercontent.com/assets/6491631/3006761/4d5d56f6-de49-11e3-9e4d-862366f8ffc1.png)

**Comment by ariel1974** [comment]
טופל כבר בגרסה ששלחתי אתמול
