### ISSUE TITLE
מחיקת עוגן בתוך טקסט

### ISSUE THREAD

**Issue by natan1957** [ariel1974/mymentor#102]
כאשר מסמנים טקסט הכולל עוגן ומוחקים, או מוסיפים טקסט הכולל מעבר/ים, המערכת מוציאה הודעת אזהרה... ואם המשתמש מאשר, נוצר הבדל בין עוגנים למעברים ובלאגן.
אבל, אם אתה מצליח לזהות כזה אירוע, האם אתה יכול פשוט למנוע אותו ?
להוציא הודעת שגיאה עם הסבר שלפני מחיקת הקטע, יש להסיר את המעברים שבתוכו.
זה ימנע את הבלאגן.
זה למעט המקרים של מחיקה והוספה של עוגנים בסביבה של אחרי העוגן האחרון שתוזמן.

דרך אגב, כיום, גם אם מוסיפים עוגן אחרי העוגן האחרון שתוזמן, יוצאת הודעת אזהרה וזה לא נכון.
במקרה כזה לא מתווסף או נגרע מעבר וזה בסדר.

**Comment by natan1957** [comment]
האם הטקסט הזה מגיע מטבלה ?
אני לא מוצא אותו בטבלת הטקסטים...
![image](https://cloud.githubusercontent.com/assets/6491631/2963985/652bdd22-dae1-11e3-83c0-50c0c1e5ee08.png)

**Comment by natan1957** [comment]
המנגנון לא אמור לחסום הוספה או גדיעה של טקסטים עם עוגנים, באזור שעדיין לא תוזמן.
זאת אומרת שניתן לבצע את פעולת ההוספה או הגריעה הידנית אחרי העוגן האחרון שיש לו תזמון.

**Comment by natan1957** [comment]
האם ניתן לצבוע את המעברים על פי צבע העוגן? 
זאת אומרת אדום סגול ירוק וצהוב ?
העוגן הראשון והאחרון יישארו בצבע הנוכחי.

**Comment by ariel1974** [comment]
הטקסט מטבלה פנימית
לחשוף אותו בטבלת הסטרינגים ?

ניתן לצבוע את המעברים - הערכה של 3 שעות פיתוח

**Comment by ariel1974** [comment]
"זאת אומרת שניתן לבצע את פעולת ההוספה או הגריעה הידנית אחרי העוגן האחרון שיש לו תזמון"
אני לא מבין איך לעשות את זה

**Comment by natan1957** [comment]
כפי שהוספה ממוכנת של עוגן באזור שלא תוזמן לא מוסיפה מעבר, כך יש לזהות הוספות וגריעות ידניות של עוגנים באזור שטרם תוזמן ולאפשר אותן.

**Comment by natan1957** [comment]
בהחלט לחשוף את הטקסטים בטבלת הסטרינגים...
זה אמור להיות נכון לגבי כל ההודעות מהסוג הזה.

**Comment by natan1957** [comment]
בשלב זה לא לצבוע מעברים.

**Comment by ariel1974** [comment]
לא כל הודעה אני חושף - רק מה שצריך

**Comment by ariel1974** [comment]
הוספתי הודעה
STD_MANUALLY_ANCHORS_VALIDATION

**Comment by natan1957** [comment]
מה קורה עם זה?
מה אתה לא מבין ?

2014-05-15 23:21 GMT+03:00 Ariel Illouz notifications@github.com:

**Comment by ariel1974** [comment]
הבנתי מה אתה רוצה 
אני לא מצליח למצוא נוסחה למצב הזה. אולי תאיר את עיני

**Comment by natan1957** [comment]
אם אני מוסיף עוגן באופן ממוכן בין עוגנים שתוזמנו, אתה מוסיף מעבר בין שני המעברים. אם אני מוסיף עוגן באופן ממוכן באזור שטרם תוזמן, אתה לא מוסיף מעבר. זו ההתנהגות הנוכחית והיא נכונה. 
מכאן אני מבין, שאתה יודע להבחין בין אזור שתוזמן לאזור שטרם תוזמן. 
על פי אותה אבחנה, יש להרשות הוספה או גריעה ידנית של עוגנים בסביבה שטרם תוזמנה. 
האם הארתי...

**Comment by ariel1974** [comment]
אני יודע להבחין בשמע, אני לא יודע להבחין בטקסט ,הכל פלואידי משתנה צריך אלגוריתם לא פשוט בכלל כדי לעלות על מצבים כאלו
