### ISSUE TITLE
חלוקת מילים

### ISSUE THREAD

**Issue by natan1957** [ariel1974/mymentor#103]
חלוקה למילים אוטומטית לא פועלת

**Comment by natan1957** [comment]
בהוספת חלוקה למילים אוטומטית, אחרי חלוקה ידנית
![image](https://cloud.githubusercontent.com/assets/6491631/3004906/9ca65206-ddc4-11e3-9b6a-d8d953c5dcd2.png)

**Comment by natan1957** [comment]
חלוקה אוטומטית לא אמורה לדרוס חלוקה ידנית
למיטב זכרוני זה טופל מזמן והתקלקל...
חלוקת מילים לא צריכה לדרוס את חלוקת המשפטים והפסקאות
![image](https://cloud.githubusercontent.com/assets/6491631/3006745/b842684c-de46-11e3-9f84-6ffeca8e36cf.png)

**Comment by ariel1974** [comment]
יטופל מחר

**Comment by natan1957** [comment]
תודה.
תעבור בבקשה גם על שאר התקלות הפתוחות (אלה שעדיין לא טיפלת או שהורדתי מהן את
התג הירוק).
מחר אבדוק את הגרסה החדשה.

נתן.

**Comment by ariel1974** [comment]
נראה לי כבר טיפלתי בזה - בדוק שוב אצלי לא משתחזר

**Comment by natan1957** [comment]
יש לאפשר לרשום בשדות החלוקה רצף אותיות כגון "אבג." או "אם" או "ע " (כולל רווח) . כיום הוא מתייחס לאות אחת בלבד.

אם אני מנסה להעתיק רצף מהטקסט לאחד השדות באמצעות קונטרול-סי וקונטרול-וי, הוא מעתיק את זה לאזור הקליפ במקום לתוך השדה. למרות שהסמן בשדה.

**Comment by ariel1974** [comment]
במקור ביקשת תו אחד. לשם תמיכה במספר תוים הייתי צריך לשכתב את כל הלוגיקה
ולכן עלולים לצוף באגים חדשים, לתשומת לבך

**Comment by natan1957** [comment]
זה לא עובד.
אני מצרף טקסט כדי שתוכל לבדוק.
הוא לא מזהה נקודותיים. כשאני מנסה להעתיק נקודותיים מהטקסט לשדה החלוקה, הוא מעתיק אותם לתוך הטקסט ואז לא מאפשר מחיקה עם מקש דל או בק.

א וַיְדַבֵּ֨ר יְהוָ֧ה אֶל־מֹשֶׁ֛ה בְּמִדְבַּ֥ר סִינַ֖י בְּאֹ֣הֶל מוֹעֵ֑ד בְּאֶחָד֩ לַחֹ֨דֶשׁ הַשֵּׁנִ֜י בַּשָּׁנָ֣ה הַשֵּׁנִ֗ית לְצֵאתָ֛ם מֵאֶ֥רֶץ מִצְרַ֖יִם לֵאמֹֽר׃ ב שְׂא֗וּ אֶת־רֹאשׁ֙ כָּל־עֲדַ֣ת בְּנֵֽי־יִשְׂרָאֵ֔ל לְמִשְׁפְּחֹתָ֖ם לְבֵ֣ית אֲבֹתָ֑ם בְּמִסְפַּ֣ר שֵׁמ֔וֹת כָּל־זָכָ֖ר לְגֻלְגְּלֹתָֽם׃ ג מִבֶּ֨ן עֶשְׂרִ֤ים שָׁנָה֙ וָמַ֔עְלָה כָּל־יֹצֵ֥א צָבָ֖א בְּיִשְׂרָאֵ֑ל תִּפְקְד֥וּ אֹתָ֛ם לְצִבְאֹתָ֖ם אַתָּ֥ה וְאַֽהֲרֹֽן׃ ד וְאִתְּכֶ֣ם יִֽהְי֔וּ אִ֥ישׁ אִ֖ישׁ לַמַּטֶּ֑ה אִ֛ישׁ רֹ֥אשׁ לְבֵית־אֲבֹתָ֖יו הֽוּא׃ ה וְאֵ֨לֶּה֙ שְׁמ֣וֹת הָֽאֲנָשִׁ֔ים אֲשֶׁ֥ר יַֽעַמְד֖וּ אִתְּכֶ֑ם לִרְאוּבֵ֕ן. אֱלִיצ֖וּר בֶּן־שְׁדֵיאֽוּר׃ ו לְשִׁמְע֕וֹן. שְׁלֻֽמִיאֵ֖ל בֶּן־צוּרִֽישַׁדָּֽי׃ זלִֽיהוּדָ֕ה נַחְשׁ֖וֹן בֶּן־עַמִּֽינָדָֽב׃׃ ח לְיִ֨שָּׂשכָ֔ר נְתַנְאֵ֖ל בֶּן־צוּעָֽר׃ ט לִזְבוּלֻ֕ן אֱלִיאָ֖ב בֶּן־חֵלֹֽן׃ י לִבְנֵ֣י יוֹסֵ֔ף לְאֶפְרַ֕יִם אֱלִֽישָׁמָ֖ע בֶּן־עַמִּיה֑וּד לִמְנַשֶּׁ֕ה גַּמְלִיאֵ֖ל בֶּן־פְּדָהצֽוּר׃ יאלְבִ֨נְיָמִ֔ן אֲבִידָ֖ן בֶּן־גִּדְעֹנִֽי׃ יב לְדָ֕ן אֲחִיעֶ֖זֶר בֶּן־עַמִּֽישַׁדָּֽי׃ יג לְאָשֵׁ֕ר פַּגְעִיאֵ֖ל בֶּן־עָכְרָֽן׃ יד לְגָ֕ד אֶלְיָסָ֖ף בֶּן־דְּעוּאֵֽל׃ טו לְנַ֨פְתָּלִ֔י אֲחִירַ֖ע בֶּן־עֵינָֽן׃ טז אֵ֚לֶּה קריאי (קְרוּאֵ֣י) הָֽעֵדָ֔ה נְשִׂיאֵ֖י מַטּ֣וֹת אֲבוֹתָ֑ם רָאשֵׁ֛י אַלְפֵ֥י יִשְׂרָאֵ֖ל הֵֽם׃ יז וַיִּקַּ֥ח מֹשֶׁ֖ה וְאַֽהֲרֹ֑ן אֵ֚ת הָֽאֲנָשִׁ֣ים הָאֵ֔לֶּה אֲשֶׁ֥ר נִקְּב֖וּ בְּשֵׁמֹֽת׃

**Comment by ariel1974** [comment]
תקנתי, נסה שוב

**Comment by natan1957** [comment]
נשבע לך לא עובד, בחיאת עיוני לא עובד...

**Comment by ariel1974** [comment]
הבעיה עם הנקודותיים ? אני אומר לך למה...אלו נקודותיים של המקרא או משהו, זה לא רגיל

**Comment by natan1957** [comment]
זה עבד קודם...

**Comment by natan1957** [comment]
כשאני מעתיק מקובץ המקור את הנקודותיים ומדביק בסטודיו, הוא מכניס את העוגנים לפני הנקודותיים במקום אחרי
![image](https://cloud.githubusercontent.com/assets/6491631/3423660/b50feeaa-ffa3-11e3-9e25-23809da92678.png)

**Comment by natan1957** [comment]
אריאל,
אני מצרף קובץ טקסט שבו חלק מהנקודותיים הסטודיו מזהה וחלק לו. זה עשוי לעזור
לך למצא את הבעיה.
בנוסף, את אלה שהוא מזהה הוא קובע את העוגן לפני הנקודותיים במקום אחרי.

נתן.

2014-06-29 9:33 GMT+03:00 Natan nhelfman@gmail.com:

> זה עבד קודם...
> 
> Sent from my iPhone
>

**Comment by ariel1974** [comment]
תוקן

**Comment by natan1957** [comment]
הועבר לסעף 121
