### ISSUE TITLE
מחיקת כל העוגנים מהתפריט

### ISSUE THREAD

**Issue by natan1957** [ariel1974/mymentor#104]
ניסיון מחיקה ראשון מוציא את ההודעה הזאת, לא מוחק עוגנים, אבל מוחק חלק מהמעברים:
![image](https://cloud.githubusercontent.com/assets/6491631/3006762/a4c710b2-de49-11e3-8fd2-0aa3280f776d.png)
![image](https://cloud.githubusercontent.com/assets/6491631/3006763/bee437ae-de49-11e3-88d8-20f6ec07264e.png)

אם זה מתבצע ממסך תזמון, נמחקים כל העוגנים והמעברים, אבל העוגנים ממשיכים להופיע עד לביצוע ריפרש ע"י מעבר לטקסט וחזרה
![image](https://cloud.githubusercontent.com/assets/6491631/3006768/80c6280a-de4a-11e3-94e3-20d7df253ca3.png)

**Comment by natan1957** [comment]
התקלה של מחיקה ממסך תזמון עדיין לא טופלה

**Comment by ariel1974** [comment]
אצלי זה לא משתחזר, הייתי על מסך תזמון, ביצעתי מחיקה מהתפריט - כל המעברים נעלמו מהגרף

**Comment by natan1957** [comment]
![image](https://cloud.githubusercontent.com/assets/6491631/3074318/23b7a3a6-e335-11e3-9bff-56ee3c6d34ed.png)
