### ISSUE TITLE
פרסום שיעור בעולם תוכן "קריאה"

### ISSUE THREAD

**Issue by natan1957** [ariel1974/mymentor#105]
פתחתי עולם תוכן "קריאה" והעברתי את עצמי אליו.
פרסמתי שיעור בהצלחה.
השיעור התפרסם עם עולם התוכן תורה.
אני שיניתי ידנית...
בנוסף, במקרה ושם קטגוריה מסוים בעולם הספציפי ריק, אין להציג את שדה הקלט לאותה הקטגוריה.

**Comment by ariel1974** [comment]
פספסת איזה קשר בטבלאות, אין אצלי שום דבר צרוב בקוד

**Comment by ariel1974** [comment]
מה קורה עם זה ?

**Comment by natan1957** [comment]
בדקתי פרסום בשני עולמות שונים ויצא בסדר.
אבל אם אני פותח קובץ שנשמר קודם בעולם אחר, ומפרסם אותו, הוא לא מתפרסם בעולם הנוכחי אלא מעדכן את הקליפ מהעולם הקודם.
זה, במקום להקים קליפ חדש בעולם הנוכחי.

**Comment by ariel1974** [comment]
הוספתי הודעה מתאימה
STD_CONTENT_TYPE_NOT_MATCH

**Comment by natan1957** [comment]
תסביר לי מה המשמעות של ההודעה... "ערך זה השתנה בקליפ". מה קורה אם אני מבצע שמירה? האם הקליפ עובר לעולם החדש?

**Comment by natan1957** [comment]
![image](https://cloud.githubusercontent.com/assets/6491631/3079425/cb5d181a-e499-11e3-9c0a-148dd787581e.png)

**Comment by natan1957** [comment]
שלחתי לך את הקובץ לבדיקה

**Comment by ariel1974** [comment]
תשנה את הטקסט של ההודעה, או שאתה לא רוצה להציג הודעה בכלל ??

**Comment by natan1957** [comment]
בתכלס, אני לא מבין מה קורה כאשר אני פותח קובץ שבמקור הוקם ונשמר בעולם אחר.

**Comment by ariel1974** [comment]
הוא רק מתריע שהעולם ישתנה, ואם תשמור את הקליפ - העולם יתעדכן.

2014-06-03 15:21 GMT+03:00 natan1957 notifications@github.com:

**Comment by natan1957** [comment]
יתעדכן לעולם הנוכחי?

**Comment by ariel1974** [comment]
כן

**Comment by ariel1974** [comment]
ניתן לסגור את הסיפור הזה

**Comment by natan1957** [comment]
בהודעה רשמת שהעולם השתנה.
מההסבר שלך אני מבין שהעולם ישתנה במידה ותתבצע שמירה.
מה נכון?

**Comment by ariel1974** [comment]
העולם השתנה בזיכרון הקליפ. אם תשמור - זה ישמר, לא תשמור לא ישמר.
