### ISSUE TITLE
מחיקת טקסט שהעוגנים הוסרו ממנו

### ISSUE THREAD

**Issue by natan1957** [ariel1974/mymentor#106]
הסרתי את כל העוגנים באופן ממוכן ואני מנסה למחוק את הטקסט ומקבל את ההודעה שלא ניתן.
מסתבר שהמעבר הראשון והאחרון לא הוסרו.
![image](https://cloud.githubusercontent.com/assets/6491631/3017035/1b9e17f4-df75-11e3-88b0-b2bb4800b178.png)

**Comment by natan1957** [comment]
עכשיו כל המעברים נעלמים אבל עדיין לא ניתן למחוק את כל הטקסט
![image](https://cloud.githubusercontent.com/assets/6491631/3046669/ac6d44fa-e12b-11e3-9111-0d0c7c3eace5.png)

**Comment by ariel1974** [comment]
לא מצליח לשחזר

**Comment by natan1957** [comment]
קח את הפטרת שגב מקוצר,
בטל את כל העוגנים
נסה לסמן את כל הטקסט ולמחוק אותו.
אל תשאיר אפילו תו אחד. גם לא רווחים.

**Comment by ariel1974** [comment]
זה לא טופל ?

**Comment by ariel1974** [comment]
<img src="http://markdalgleish.github.io/presentation-build-wars-gulp-vs-grunt/images/gif/angry-amy.gif">

**Comment by natan1957** [comment]
אחרי ביטול כל הטקסט, אני עובר למסך תזמון רואה ש התחלה וסוף נמצאים. מבחינתי זה הסדר...
אני מפעיל פליי ומקבל את הודעת השגיאה

![image](https://cloud.githubusercontent.com/assets/6491631/3159774/154e565a-eb16-11e3-9f8e-a33be58aac17.png)

איתור באגים בשיטת just-in-time (JIT) במקום תיבת דו-שיח זו.

*************\* טקסט החריג **************
System.NullReferenceException: ההפניה לאובייקט לא הוגדרה למופע של אובייקט.
   ב-  MyMentor.Forms.FormStudio.timerFirstAnchorScheduling_Tick(Object sender, EventArgs e)
   ב-  System.Windows.Forms.Timer.OnTick(EventArgs e)
   ב-  System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   ב-  System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

*************\* הרכבות שנטענו **************
mscorlib
   גירסת הרכבה: 4.0.0.0
   גירסת Win32: 4.0.30319.34014 built by: FX45W81RTMGDR

##    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll

MyMentor
   גירסת הרכבה: 9.0.8.5
   גירסת Win32: 9.0.8.5

##    CodeBase: file:///C:/Program%20Files%20(x86)/MyMentor%20V2/MyMentor.exe

Parse
   גירסת הרכבה: 1.2.10.0
   גירסת Win32: 1.2.10.0

##    CodeBase: file:///C:/Program%20Files%20(x86)/MyMentor%20V2/Parse.DLL

System.Runtime
   גירסת הרכבה: 4.0.0.0
   גירסת Win32: 4.0.30319.33440

##    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Runtime.dll

System.Windows.Forms
   גירסת הרכבה: 4.0.0.0
   גירסת Win32: 4.0.30319.33440 built by: FX45W81RTMREL

##    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll

System.Drawing
   גירסת הרכבה: 4.0.0.0
   גירסת Win32: 4.0.30319.33440 built by: FX45W81RTMREL

##    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll

System
   גירסת הרכבה: 4.0.0.0
   גירסת Win32: 4.0.30319.34003 built by: FX45W81RTMGDR

##    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll

System.Collections
   גירסת הרכבה: 4.0.0.0
   גירסת Win32: 4.0.30319.33440

##    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Collections/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Collections.dll

System.Threading.Tasks
   גירסת הרכבה: 4.0.0.0
   גירסת Win32: 4.0.30319.33440

##    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Threading.Tasks/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Threading.Tasks.dll

Parse.NetFx45
   גירסת הרכבה: 1.2.10.0
   גירסת Win32: 1.2.10.0

##    CodeBase: file:///C:/Program%20Files%20(x86)/MyMentor%20V2/Parse.NetFx45.DLL

System.Net.Primitives
   גירסת הרכבה: 4.0.0.0
   גירסת Win32: 4.0.30319.33440

##    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Net.Primitives/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Net.Primitives.dll

System.IO
   גירסת הרכבה: 4.0.0.0
   גירסת Win32: 4.0.30319.33440

##    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.IO/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.IO.dll

System.Configuration
   גירסת הרכבה: 4.0.0.0
   גירסת Win32: 4.0.30319.33440 built by: FX45W81RTMREL

##    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll

System.Xml
   גירסת הרכבה: 4.0.0.0
   גירסת Win32: 4.0.30319.33440 built by: FX45W81RTMREL

##    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll

System.Reflection
   גירסת הרכבה: 4.0.0.0
   גירסת Win32: 4.0.30319.33440

##    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Reflection/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Reflection.dll

System.Threading
   גירסת הרכבה: 4.0.0.0
   גירסת Win32: 4.0.30319.33440

##    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Threading/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Threading.dll

System.ObjectModel
   גירסת הרכבה: 4.0.0.0
   גירסת Win32: 4.0.30319.33440

##    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ObjectModel/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.ObjectModel.dll

System.Core
   גירסת הרכבה: 4.0.0.0
   גירסת Win32: 4.0.30319.33440 built by: FX45W81RTMREL

##    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll

System.Reflection.Extensions
   גירסת הרכבה: 4.0.0.0
   גירסת Win32: 4.0.30319.33440

##    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Reflection.Extensions/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Reflection.Extensions.dll

mscorlib.resources
   גירסת הרכבה: 4.0.0.0
   גירסת Win32: 4.0.30319.33440 built by: FX45W81RTMREL

##    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_he_b77a5c561934e089/mscorlib.resources.dll

System.Globalization
   גירסת הרכבה: 4.0.0.0
   גירסת Win32: 4.0.30319.33440

##    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Globalization/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Globalization.dll

System.Runtime.Extensions
   גירסת הרכבה: 4.0.0.0
   גירסת Win32: 4.0.30319.33440

##    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Extensions/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Runtime.Extensions.dll

System.Text.RegularExpressions
   גירסת הרכבה: 4.0.0.0
   גירסת Win32: 4.0.30319.33440

##    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Text.RegularExpressions/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Text.RegularExpressions.dll

AudioDjStudio
   גירסת הרכבה: 1.0.0.0
   גירסת Win32: 6.4.2.3

##    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/AudioDjStudio/1.0.0.0__6dd52dbb299cc1b2/AudioDjStudio.dll

AudioSoundEditor
   גירסת הרכבה: 1.0.0.0
   גירסת Win32: 4.1.1.0

##    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/AudioSoundEditor/1.0.0.0__6dd52dbb299cc1b2/AudioSoundEditor.dll

AudioSoundRecorder
   גירסת הרכבה: 1.0.0.0
   גירסת Win32: 6.1.2.0

##    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/AudioSoundRecorder/1.0.0.0__6dd52dbb299cc1b2/AudioSoundRecorder.dll

System.Windows.Forms.resources
   גירסת הרכבה: 4.0.0.0
   גירסת Win32: 4.0.30319.33440 built by: FX45W81RTMREL

##    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_he_b77a5c561934e089/System.Windows.Forms.resources.dll

Accessibility
   גירסת הרכבה: 4.0.0.0
   גירסת Win32: 4.0.30319.33440 built by: FX45W81RTMREL

##    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll

System.Linq
   גירסת הרכבה: 4.0.0.0
   גירסת Win32: 4.0.30319.33440

##    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Linq/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Linq.dll

System.Text.Encoding
   גירסת הרכבה: 4.0.0.0
   גירסת Win32: 4.0.30319.33440

##    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Text.Encoding/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Text.Encoding.dll

System.Net.Http
   גירסת הרכבה: 4.0.0.0
   גירסת Win32: 4.0.30319.33440 built by: FX45W81RTMREL

##    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Net.Http/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Net.Http.dll

System.Linq.Expressions
   גירסת הרכבה: 4.0.0.0
   גירסת Win32: 4.0.30319.33440

##    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Linq.Expressions/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Linq.Expressions.dll

Anonymously Hosted DynamicMethods Assembly
   גירסת הרכבה: 0.0.0.0
   גירסת Win32: 4.0.30319.34014 built by: FX45W81RTMGDR

##    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/mscorlib/v4.0_4.0.0.0__b77a5c561934e089/mscorlib.dll

Ionic.Zip
   גירסת הרכבה: 1.9.1.8
   גירסת Win32: 1.9.1.8

##    CodeBase: file:///C:/Program%20Files%20(x86)/MyMentor%20V2/Ionic.Zip.DLL

Newtonsoft.Json
   גירסת הרכבה: 4.5.0.0
   גירסת Win32: 5.0.8.16617

##    CodeBase: file:///C:/Program%20Files%20(x86)/MyMentor%20V2/Newtonsoft.Json.DLL

Microsoft.GeneratedCode
   גירסת הרכבה: 1.0.0.0
   גירסת Win32: 4.0.30319.33440 built by: FX45W81RTMREL

##    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll

System.Numerics
   גירסת הרכבה: 4.0.0.0
   גירסת Win32: 4.0.30319.33440 built by: FX45W81RTMREL

##    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll

System.ComponentModel.DataAnnotations
   גירסת הרכבה: 4.0.0.0
   גירסת Win32: 4.0.30319.33440

##    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ComponentModel.DataAnnotations/v4.0_4.0.0.0__31bf3856ad364e35/System.ComponentModel.DataAnnotations.dll

System.Runtime.Serialization
   גירסת הרכבה: 4.0.0.0
   גירסת Win32: 4.0.30319.33440 built by: FX45W81RTMREL

##    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll

System.Xml.Linq
   גירסת הרכבה: 4.0.0.0
   גירסת Win32: 4.0.30319.33440 built by: FX45W81RTMREL

##    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll

System.Data
   גירסת הרכבה: 4.0.0.0
   גירסת Win32: 4.0.30319.33440 built by: FX45W81RTMREL

##    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll

HtmlAgilityPack
   גירסת הרכבה: 1.4.6.0
   גירסת Win32: 1.4.6.0

##    CodeBase: file:///C:/Program%20Files%20(x86)/MyMentor%20V2/HtmlAgilityPack.DLL

System.resources
   גירסת הרכבה: 4.0.0.0
   גירסת Win32: 4.0.30319.33440 built by: FX45W81RTMREL

##    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.resources/v4.0_4.0.0.0_he_b77a5c561934e089/System.resources.dll

*************\* איתור באגים בשיטת JIT **************
כדי להפוך את  just-in-time (JIT) debugging לזמין, the .config יש להגדיר
בקובץ התצורה של היישום או המחשב (machine.config) את הערך
 system.windows.forms במקטע jitDebugging.
כמו כן, יש לבצע ליישום קומפילציה עם  jitdebugging
זמין.

For לדוגמה:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

כאשר JIT debugging זמין, כל חריג שאינו מטופל
יישלח אל JIT debugger הרשום במחשב
במקום שיטופל על-ידי תיבת דו-שיח זו.

**Comment by ariel1974** [comment]
<img src="http://markdalgleish.github.io/presentation-build-wars-gulp-vs-grunt/images/gif/no-answer.gif">

**Comment by natan1957** [comment]
מזל שיש לי עוד מצברוח מהיומולדת...

**Comment by ariel1974** [comment]
טופל
