### ISSUE TITLE
שונות...

### ISSUE THREAD

**Issue by natan1957** [ariel1974/mymentor#107]
במצב מקור יש להעלים גם את הנחייה ואת מבצע ומבצע באנגלית

ליד שם הקבוצה מבצע יש להוסיף בסוגריים (כשהמבצע איננו המורה)    ז

אם שם קטגוריה ריק, אין להציג אותה ואין לחייב אותה.

יש לחייב את שדות הקטגוריות החובה  כרגע, הבדיקה היא שמספיק שהוכנסה קטגוריה אחת מהארבע

יש להציג את עולם התוכן בשורת הסטטוס או ליד שם המשתמש המחובר

 במצב מקור, יש להוסיף לתחילת שם הקובץ הנשמר  את המילה מקור

את הטקסט נעילות מקטעים לשנות ל מקטעי לימוד

את מקטעי הלימוד לשנות ל: פסקאות, משפטים, קטעים, מילים.

בשלבי לימוד לשנות ל: הקשב לי, עכשיו נקרא יחד, הקשב לי שוב, עכשיו אתה

יש לחייב הזנת תאריך קריאה שיהיה גדול מתאריך היום

לא ברור מה זה פורסם ב ... האם אמור להציג את מועד הפרסום האחרון? זה לא קורה.

פרסום צריך לבצע גם שמירת קובץ.

מילות מפתח... מופרדים עם פסיק? או מספיק רווח? יש להסביר או לתת דוגמה.

לשנות תיאור ל תיאור באנגלית

תאריך תפוגה - לבטל.

להגדיל את חלונות ההקלדה של תיאור ותיאור באנגלית, אפשר להזיז את תאריכי קריאה מתחת למבצע. 
לחלופין, בלחיצה על אחד החלונות להקפיץ חלון גדול להקלדה ובלחיצה על סגור להעביר את תוכן ההקלדה לחלון הקטן.

**Comment by natan1957** [comment]
להזיז את שדה התאריך מעל לרשימת התאריכים. - מסומן בכחול
להעלים את כל השדות האלה (באדום) בהתאם לשדה 
readingDates
ברשומת עולם שצריך להיות 
true

![image](https://cloud.githubusercontent.com/assets/6491631/3074422/2766ba80-e33c-11e3-9d81-8446260e5689.png)

**Comment by ariel1974** [comment]
אין שדה כזה בטבלת WorldContentType

**Comment by natan1957** [comment]
יש.

**Comment by ariel1974** [comment]
נשבע לך אין

**Comment by natan1957** [comment]
אבדוק.

**Comment by natan1957** [comment]
נשבע לך היה...
![image](https://cloud.githubusercontent.com/assets/6491631/3075439/f5d05c2e-e377-11e3-98fd-0fd1f6fce5ec.png)

**Comment by ariel1974** [comment]
הוספת אותו עכשיו חנטריש...

**Comment by natan1957** [comment]
![image](https://cloud.githubusercontent.com/assets/6491631/3076389/b0f9a244-e3d7-11e3-82ed-b6be7ee752d0.png)
