### ISSUE TITLE
קטגוריה נעלמה

### ISSUE THREAD

**Issue by natan1957** [ariel1974/mymentor#108]
![image](https://cloud.githubusercontent.com/assets/6491631/3074387/12d931f8-e33a-11e3-95aa-9fbc66aa4ab1.png)

**Comment by ariel1974** [comment]
אמרת להסתיר קטגוריות שאין בהם ערכים

**Comment by natan1957** [comment]
קטגוריות שאין להן שם קטגוריה.

**Comment by ariel1974** [comment]
תוקן

**Comment by natan1957** [comment]
![image](https://cloud.githubusercontent.com/assets/6491631/3076968/9cc92e98-e409-11e3-857d-a163d800c359.png)

**Comment by ariel1974** [comment]
משמע אין ערכים - מה שביקשת

**Comment by natan1957** [comment]
עוד פעם אתה... עם השטויות האלה... על איזה ערך אתה מדבר? תוכן או שם?

**Comment by ariel1974** [comment]
כשאין ערכים בתיבות רשימה - אני מסתיר אותן

**Comment by natan1957** [comment]
הכלל הוא כשאין שם קטגוריה בטבלת השמות...

**Comment by ariel1974** [comment]
<img src="http://markdalgleish.github.io/presentation-build-wars-gulp-vs-grunt/images/gif/clap.gif">

**Comment by natan1957** [comment]
![image](https://cloud.githubusercontent.com/assets/6491631/3090107/91879608-e587-11e3-9540-37a400b562cc.png)

**Comment by natan1957** [comment]
ילד כאפות... בטח חזרו לו הקטגוריות... מעניין איזה גרסה הוא מפעיל...

**Comment by natan1957** [comment]
![image](https://cloud.githubusercontent.com/assets/6491631/3109455/a0edb7d6-e699-11e3-8656-25807adeafab.png)
