### ISSUE TITLE
שם קובץ

### ISSUE THREAD

**Issue by natan1957** [ariel1974/mymentor#109]
במצב מקור, יש להוסיף לתחילת שם הקובץ הנשמר את המילה מקור

זה לא עובד.
במקום זה להכניס את שם השיעור שנוצר לתוך שדה שם הקובץ
אני אוסיף את התוספת(מקור) בטבלת השרשור...

פרסום צריך לבצע גם שמירת קובץ. .
אם טרם נשמר  יש לפתוח חלון שמירת קובץ עם שם קובץ מוצע שווה לשם השיעור
אם קובץ כבר נשמר ובמהלך שינויים במסך הפרסום השתנה שם השיעור, וזה עשוי לגרור שינוי שם קובץ, 
יש לפתוח תיבת בחירה עם הודעה "שם השיעור שונה" והאפשרויות
החלף קובץ לשם החדש
שמור קובץ בשם הקיים
שמור חשד והשאר קיים
פתח חלון שמירת קובץ

באפשרות האחרונה יש לפתוח את החלון.

**Comment by ariel1974** [comment]
סיימתי את הכל חוץ מזה כי זו תוספת עם עלות של שעתיים עבודה
<i>
אם קובץ כבר נשמר ובמהלך שינויים במסך הפרסום השתנה שם השיעור, וזה עשוי לגרור שינוי שם קובץ, 
יש לפתוח תיבת בחירה עם הודעה "שם השיעור שונה" והאפשרויות
החלף קובץ לשם החדש
שמור קובץ בשם הקיים
שמור חשד והשאר קיים
פתח חלון שמירת קובץ

באפשרות האחרונה יש לפתוח את החל
</i>
לבצע ?

**Comment by natan1957** [comment]
אז תציע משהו הגיוני כמו להקפיץ את חלון השמירה המקום להודיע שתריך לשמור... ולהכניס את שם השיעור לשם הקובץ.

**Comment by ariel1974** [comment]
אני יכול להקפיץ לך את חלון השמירה עם השם להחלפה, יהיה שם לחצן ביטול

**Comment by natan1957** [comment]
עם שם השיעור בשדה שם הקובץ

**Comment by natan1957** [comment]
עכשיו, אחרי ששמרתי את הקובץ, בכל שינוי באחת הקטגוריות קופץ מסך שמירה.
בשינוי פרמטרים אחרים כגון מחיר או סוג הנחייה, זה לא קורה...
מסך השמירה צריך לקפוץ עם לחיצה על פרסום ובמידה ובוצעו שינויים שלא נשמרו.

**Comment by ariel1974** [comment]
אוקי

**Comment by natan1957** [comment]
מה שקורה, אם רוצים לפרסם כאשר לא כל השדות מולאו, קופצת הודעת שגיאה, אבל זה אחרי שהקובץ נשמר. ואז מתקנים, ושומרים שוב. ואם עדיין שגיאה, מתקנים שוב ושומרים.... נוצרת ערמה של קבצים לא נחוצים...
יש להחליף את הסדר בין שמירת הקובץ לבדיקות החוקיות.
בלחיצה על פרסום, יש קודם לבצע בדיקת חוקיות ואם שגוי, יש להודיע על שגיאה.
אם אין שגיאות ונדרש לשמור קובץ, יש להקפיץ מסך שמירה.
אחרי השמירה יש להקפיץ מסך אישור פרסום..

האם ניתן, בשמירה, למחוק את הקובץ שנשמר בפעם הקודמת אם שמו השתנה כמובן...
