### ISSUE TITLE
שם מקור

### ISSUE THREAD

**Issue by natan1957** [ariel1974/mymentor#11]
שם המקור אמור להכיל גם את ההערות.
ראשי ופרשה מוחלפים בניהם בשרשור השם.
יש לקחת בחשבון שלמעשה נוצרים שני שמות , האחד בעברית והשני באנגלית. השם באנגלית יוצג בממשק האנגלי.

**Comment by ariel1974** [comment]
אתה מתכוון באתר של תום באנגלית? אתה רוצה שיציג תמיד שדות הערה באנגלית וכו'?

**Comment by natan1957** [comment]
לא, אני מתכוון לסטודיו.
הוא צריך לתמוך גם בשפות נוספות ובשלב ראשון באנגלית.
במקרה כזה, הקטגוריות יוצגו בגרסה האנגלית וההערה האנגלית תצורף.

כשהיית בחו"ל שלחתי לך להתייחסות את עניין השפות בטבלאות. סיכמתי עם תום שהשפות יופיעו בשדות נוספים ברשומה ולא ברשומות נפרדות עם עמודת שפה.

**Comment by ariel1974** [comment]
התחייבתי להכנת תשתית לתמיכה בשפות - לא תמיכה מלאה באנגלית בשלב ראשון

**Comment by natan1957** [comment]
לא מבין מה ההבדל בין תשתית לתמיכה מלאה.
הדרישה לשפת ממשק עברית אנגלית היא מהיום הראשון, עם לאפליקציה, גם לפורטל וגם לסטודיו.

**Comment by natan1957** [comment]
בכל מקרה תוכן ההערות בשתי השפות צריך להופיע התוצאות חיפוש מקורות.
 שים לב שבשם השיעור, הקטגוריה ראשי נמצאת אחרי הקטגוריה פרשה. צריך להחליף

**Comment by ariel1974** [comment]
יש לך שליטה בטבלת WorldContentTypes על תבנית השם
אתה רוצה שאוסיף עמודות הערה + הערה באנגלית
לתוצאות החיפוש ?
