### ISSUE TITLE
משהו נדפק בהתקנה

### ISSUE THREAD

**Issue by natan1957** [ariel1974/mymentor#115]
![image](https://cloud.githubusercontent.com/assets/6491631/3174477/177f62f2-ebf2-11e3-9e73-dfb893fbee07.png)

כמו פעם, ניסיתי להסיר את ההתקנה, זה נעלם מרשימת המותקנים אבל עדיין האייקון קיים ובהפעלה הוא מודיע שאין אינטרנט.
![image](https://cloud.githubusercontent.com/assets/6491631/3174805/5217427e-ebf5-11e3-8ba1-248c1e8f5be5.png)

בהתקנה חוזרת הוא מציג:
![image](https://cloud.githubusercontent.com/assets/6491631/3174829/84f818ee-ebf5-11e3-99d4-79e9e27648ff.png)

ואם אני רוצה להסיר הוא מודיע על הצלחה בתוך רגע.
![image](https://cloud.githubusercontent.com/assets/6491631/3174847/af571dec-ebf5-11e3-8e8b-a21c49a0de78.png)

והאייקון עדיין נמצא..
![image](https://cloud.githubusercontent.com/assets/6491631/3174887/052cc302-ebf6-11e3-906e-7b53175d9eab.png)

**Comment by ariel1974** [comment]
זו ההתקנה של הסטודיו הישן
היית צריך להסיר את V2

**Comment by ariel1974** [comment]
ואצלי זה עובד...מסיר והקיצור דרך נמחק כמצופה
