### ISSUE TITLE
כל עדכון מייצר קובץ חדש ושיעור חדש

### ISSUE THREAD

**Issue by natan1957** [ariel1974/mymentor#116]
אני פותח קובץ קיים שפורסם.
אני משנה את אחת הקטגוריות ומבצע שמירה.
נוצר קובץ חדש במקום לעדכן את הנוכחי או למחוק את הישן ולהקים חדש
אם אני מפרסם, נוצר שיעור חדש.
בסך הכל ביקשתי לעדכן קיים.

**Comment by ariel1974** [comment]
נתן זה מה שביקשת או שאני מפספס משהו

**Comment by natan1957** [comment]
לא. ראה הבקשה האחרונה ב אישו 109. שכבר סגור...
ביקשתי שכשמשתנה שם הקובץ כתוצאה משינוי קטגוריות או "תוספת לשם שיעור", לשמור בשם החדש ולמחוק את הישן. זה אומר למעשה לעדכן ולא להקים חדש.
ההקמה של קובץ חדש וקליפ חדש תייצר אינפלציה של קבצים וקליפים.
מצד שני נדרשת היכולת לקחת קובץ קיים ולייצר ממנו משהו חדש... אני חושב שהפתרון הנכון יהיה שני כפתורי פרסום, האחד "פרסם שיעור חדש" והשני "עדכן שיעור קיים". בעדכון יש לעדכן, זאת אומרת שבמידה ומשתנה שם קובץ יש למחוק את הישן, ולעדכן את הקליפ הקיים, ובפרסום חדש, יש להקים קובץ חדש וקליפ חדש.

**Comment by ariel1974** [comment]
לא נכון - ראה הערה קודמת שלי
#117

**Comment by natan1957** [comment]
הועבר לסעיף 120
