### ISSUE TITLE
שיבוש בהצגת קטגוריות של קובץ קיים

### ISSUE THREAD

**Issue by natan1957** [ariel1974/mymentor#117]
![image](https://cloud.githubusercontent.com/assets/6491631/3420617/703aed9c-feb4-11e3-9992-c30084fe56d2.png)

**Comment by ariel1974** [comment]
שלח לי את הקובץ

**Comment by natan1957** [comment]
שלחתי

**Comment by ariel1974** [comment]
<h1>פתחתי קובץ</h1>

![image](https://cloud.githubusercontent.com/assets/3278964/3485928/0abfe332-040e-11e4-9c9c-3ad5deb61332.png)

<h1>שיניתי מאפיין ולחצתי על פרסום</h1>

![image](https://cloud.githubusercontent.com/assets/3278964/3485934/2df2847c-040e-11e4-8d47-9df563c26ad2.png)

<h1> שמרתי - שים לב לשני הקבצים</h1>

![image](https://cloud.githubusercontent.com/assets/3278964/3485937/4ac3c87c-040e-11e4-83fe-d3cfdf2f8f1e.png)

<h1> זה מה שיש בתקיה</h1>

![image](https://cloud.githubusercontent.com/assets/3278964/3485939/7bae7d88-040e-11e4-9d10-6a53c78e4f4f.png)

**Comment by natan1957** [comment]
הועבר לסעיף 119
