### ISSUE TITLE
סילוק שדות לא נחוצים

### ISSUE THREAD

**Issue by natan1957** [ariel1974/mymentor#12]
בפרסום מקור יש לסלק את שדות ברירת המחדל ואת תאריכי קריאה.

**Comment by ariel1974** [comment]
הסרתי את תאריכי הקריאה, אני לא מבין למה אתה מתכוון שדות ברירת המחדל

**Comment by natan1957** [comment]
![image](https://f.cloud.github.com/assets/6491631/2051499/47144592-8a8a-11e3-88bd-45163177af10.png)
