### ISSUE TITLE
פרסום שיעור חדש - עדכון שיעור קיים

### ISSUE THREAD

**Issue by natan1957** [ariel1974/mymentor#120]
יש להפריד בנן שני המצבים.
בשיעור חדש, האפשרות לעדכון קיים תהיה לא זמינה.
הקשה על "עדכון שיעור קיים" תעדכן את הקבצים בספרייה (ע"י מחיקת ישן ושמירת חדש) ותעדכן את השיעור  בטבלה תוך שמירה על הזהות שלו.
הקשה על :"פרסום שעור חדש" תייצר שיעור חדש עם קבצים חדשים, גם את השיעור היה קיים.
במידה ולא השתנה שם השיעור, ז"א לא הוחלפה קטגוריה ולא השתנה "תוספת לשם שיעור" אין לאפשר שיעור חדש. יש לחייב שם שיעור יוניק.
ההודעה "האם אתה בטוח..." תתיחס לפעולה הרלוונטית, פרסום שיעור חדש או עדכון קיים.

**Comment by ariel1974** [comment]
תקנתי את הבאג במחיקת קבצים (אינפלציה)

לחצן עדכן קיים / עדכן חדש - שעת פיתוח
אנא אשר

**Comment by natan1957** [comment]
חשבתי שתמחרת הכל... תתמחר את כל השינויים כדי שאוכל לראות את כל התמונה.

2014-07-06 23:12 GMT+03:00 Ariel Illouz notifications@github.com:

**Comment by natan1957** [comment]
יש אישור

**Comment by natan1957** [comment]
האם בוצעה הפרדה לפרסום קליפ חדש ולעדכון קליפ קיים?

**Comment by ariel1974** [comment]
תסביר
"במידה ולא השתנה שם השיעור, ז"א לא הוחלפה קטגוריה ולא השתנה "תוספת לשם שיעור" אין לאפשר שיעור חדש. יש לחייב "

**Comment by natan1957** [comment]
אם תתאפשר שמירת שיעור חדש מבלי לשנות את הפרמטרים, ייוצר קליפ חדש עם שם זהה לקליפ קיים ויישמר קובץ חדש במחשב עם שם זהה לקובץ הקיים.
מערכת ההפעלה חלונות תוסיף לו (2) כדי להבדיל אותו מהקיים.
מאותו הרגע, למעשה, הדרך היחידה לדעת  פרסום של איזה קובץ ישפיע על איזה קליפ זה לנבור בתוכן.
וזה בלאגן.
לפי דעתי זה מצב לא סביר. אם אתה מפרסם קליפ חדש הוא אמור להיות שונה מהקיים כולל השם.
לכן אני מבקש למנוע כזה מצב.

**Comment by natan1957** [comment]
נמצא ב 138
