### ISSUE TITLE
ביטול הבהוב כפתורי עוגנים

### ISSUE THREAD

**Issue by natan1957** [ariel1974/mymentor#126]
יש לבטל את ההבהוב של כפתור מהבהב בעקבות כל פעולה במערכת למעט בחלון הטקסט.
זאת אומרת שכל לחיצה על פקד כלשהו יבטל את ההבהוב. כולל מינוס, כל פקדי סרגל הכלים, פקדי החלוקה האוטומטית, כפתור הבאה מהמאגר, מעבר ללשונית אחרת וכו', .
כמובן שלחיצה על צבע אחר תפעיל בו היבהוב כפי שקורה היום.

**Comment by ariel1974** [comment]
סוכם בטלפון רק על מעבר טאב לא על כל פעילויות אלו. אם כך זו שעת עבודה - אני צריך שתאשר לי

**Comment by natan1957** [comment]
אז תשאיר איך שדיברנו.

**Comment by natan1957** [comment]
הפסקת הבהוב במעבר טאב ובלחיצה על מינוס.
