### ISSUE TITLE
שם קליפ מפוצל עבור הפורטל

### ISSUE THREAD

**Issue by natan1957** [ariel1974/mymentor#127]
צריך את שם הקליפ עבור הפורטל מחולק לשניים
לשם כך הוספתי לטבלת העולמות שדות פטרן חלק1 וחלק2 לעברית ולאנגלית.
את השמות יש להכניס לשדות הרלוונטיים שהוספתי לטבלת הקליפים.

**Comment by ariel1974** [comment]
שעת פיתוח - תאשר

**Comment by natan1957** [comment]
יאללה, אין אצלך חצאי שעות?...
מאשר.

**Comment by ariel1974** [comment]
נוסף ב-9.0.9.9

**Comment by natan1957** [comment]
למה ככה ?
![image](https://cloud.githubusercontent.com/assets/6491631/3562823/ecac7056-0a0a-11e4-91c5-c8aa0c793124.png)

**Comment by ariel1974** [comment]
באג
