### ISSUE TITLE
פרסום ללא דמו וללא פרוויו

### ISSUE THREAD

**Issue by natan1957** [ariel1974/mymentor#129]
ישנם קליפים שמתפרסמים ללא...
אני שולח לך את הקובץ שפורסם לא תקין

![image](https://cloud.githubusercontent.com/assets/6491631/3549758/9fe74332-08ce-11e4-9c82-c494a6743c52.png)

**Comment by ariel1974** [comment]
ממתי הם?

**Comment by ariel1974** [comment]
אולי אלו מקורות?

**Comment by natan1957** [comment]
חדשים. תסתכל על התאריכים.

**Comment by natan1957** [comment]
לא.

**Comment by ariel1974** [comment]
מה מיוחד בהם ? אצלי הכל תקין

**Comment by natan1957** [comment]
לא ידוע לי על משהו מיוחד. שלחתי לך את הקובץ...

**Comment by natan1957** [comment]
עדיין מפרסם ללא דמו ופריוויו
שים לב שסרגל הסטטוס בפרסום לא מסיים... נתקע ככה. למרות שנותן הודעה שהפרסום הצליח
אני שולח לך שוב את הקובץ
![image](https://cloud.githubusercontent.com/assets/6491631/3551855/d990c44a-08ed-11e4-9762-df16eeb16ee9.png)

**Comment by natan1957** [comment]
זה עדיין קורה.
שלחתי לך במייל את הקבצים של הקליפים.
![image](https://cloud.githubusercontent.com/assets/6491631/3564730/f18eeba4-0a95-11e4-8bf1-0195404b170e.png)
