### ISSUE TITLE
זכירת שדות

### ISSUE THREAD

**Issue by natan1957** [ariel1974/mymentor#13]
אם אני בוחר מקור, יש לו מאפיניים כמו ראשי , פרשה,קריאה והערות.
כאשר אני מגיע לפרסום, השדות צריכים להופיע. 
למעט מקרה בו מבקשים לשמור שיעור, וסוג הקריאה של המקור לא מותר לשיעור. במקרה כזה יש לאפס את הקריאה.

**Comment by ariel1974** [comment]
אם אני לא טועה - זה לא צויין באפיון המקורי
ביקשת רק להדביק את הטקסט - אבצע זאת אבל תשים לב לשינויים שלא בתכולה המקורית

**Comment by natan1957** [comment]
אם אני פותח קובץ שפורסם ונשמר בדיסק, מכניס בו שינויים (תזמון וטקסט) ורוצה לפרסם, שדה תיאור באנגלית לא מופיע.

**Comment by ariel1974** [comment]
עדיין פתוח ? למיטב זכרוני זה תוקן
