### ISSUE TITLE
שגיאה קריטית בפתיחת הסטודיו

### ISSUE THREAD

**Issue by natan1957** [ariel1974/mymentor#131]
הסטודיו שוב מושבת. מה עשיתי עכשיו...
![image](https://cloud.githubusercontent.com/assets/6491631/3554085/32d233f6-090a-11e4-9adb-9d4f6e3962b4.png)

**Comment by ariel1974** [comment]
אצלי זה בסדר עם המשתמש שלך

**Comment by natan1957** [comment]
אני מבין שזה קרה בגלל הגדרה לא מלאה של עולם התוכן.
האם בוצע שינוי שלא ייתקע מסיבה זו אלא יוציא הודעה?

**Comment by natan1957** [comment]
??

**Comment by natan1957** [comment]
הודעה שאני מקבל עם הפעלת הסטודיו.
אני מקיש המשך וזה עובד...
![image](https://cloud.githubusercontent.com/assets/6491631/4434216/047c6416-470a-11e4-92d6-d36d6d45ccae.png)
