### ISSUE TITLE
שיעור מעולם תוכן אחר

### ISSUE THREAD

**Issue by natan1957** [ariel1974/mymentor#132]
בפתיחת השיעור הוא נותן הודעה שהוא מעולם אחר.
אני מבצע שמירה ופרסום. הוא עמור לעבור לעולם הנוכחי...
אני פותח אותו שוב, והוא שוב מודיע את אותה ההודעה.
אני מעוניין לפרסם אותו בעולם התורה.
![image](https://cloud.githubusercontent.com/assets/6491631/3564680/adffc536-0a93-11e4-9271-d38572ad07e7.png)

**Comment by ariel1974** [comment]
העולם החדש נשמר רק בעת שמירה
