### ISSUE TITLE
מערך פונטים

### ISSUE THREAD

**Issue by natan1957** [ariel1974/mymentor#133]
האם המערך לא אמור להכיל 4 מופעים? אחד לכל קובץ?
האם שני  הגדלים מתייחסים למגוון הקיים באותו הפונט?
מה היה מופיע במערך אם הייתה תערובת פונטים בקובץ?
איך זה שבמופע השני הפונט שונה? הרי הוא נלקח מאותו קובץ כמו הראשון?

![image](https://cloud.githubusercontent.com/assets/6491631/3602575/acfffaf8-0d0d-11e4-8383-58fba879920c.png)

**Comment by ariel1974** [comment]
לא. כן. כל פונט מקבל ייצוג ותחתיו הגדלים. לא מבין את השאלה.

2014-07-16 20:22 GMT+03:00 natan1957 notifications@github.com:

> האם המערך לא אמור להכיל 4 מופעים? אחד לכל קובץ?
> האם שני הגדלים מתייחסים למגוון הקיים באותו הפונט?
> מה היה מופיע במערך אם הייתה תערובת פונטים בקובץ?
> איך זה שבמופע השני הפונט שונה? הרי הוא נלקח מאותו קובץ כמו הראשון?
> 
> [image: image]
> https://cloud.githubusercontent.com/assets/6491631/3602575/acfffaf8-0d0d-11e4-8383-58fba879920c.png
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ariel1974/mymentor/issues/133.

## 

Thanks,
Ariel

**Comment by natan1957** [comment]
ביקשתי פרטים על כל קובץ מתוך 4 הקבצים. גם אם כרגע הם אמורים להכיל את אותם הפטנטים ובאותם גדלים. האם זה בא לידי ביטוי במערך?

**Comment by ariel1974** [comment]
לא מבין את השאלה, על איזה קבצים אתה מדבר

**Comment by natan1957** [comment]
1. עם ניקוד וען טעמים
2. עם ניקוד ובלי טעמים
3. בלי ניקוד ועם טעמים
4. בלי ניקוד ובלי טעמים
