### ISSUE TITLE
שמירת שיעור חדש

### ISSUE THREAD

**Issue by natan1957** [ariel1974/mymentor#135]
במהלך הכנת שיעור אני מבצע שמירה לקובץ.
בסוף ההכנה אני רוצה לפרסם כחדש.
ואז הוא לא מודיע כי לא השתנה השם.כאילו הוא כבר קליפ קיים.
קליפ נחשב קיים רק אם כבר פורסם.

כאשר אני פותח שיעור קיים, עושה שינוי ושומר כחדש\ מוקם קליפ חדש וזה טוב, אבל הקובץ הישן במחשב נמחק ובמקומו נשמר החדש.
זה לא טוב. במקרה של שמירת חדש, אין למחוק את הישן. , 
האם במקרה של מחיקת הקובץ במחשב, יש יכולת לעדכן את הקליפ?
איך ?

בעדכון שם קובץ, גם קובץ הסאונד מתעדכן אבל קובץ ה פרוויו לא

**Comment by ariel1974** [comment]
יש כאן מספר באגים ? אני לא מצליח לזהות את הבעיה, ומה שהיה מצופה
תנסה לבודד את הבעיה

**Comment by natan1957** [comment]
במהלך הכנת שיעור אני מבצע שמירה לפני הפרסום.
בסוף ההכנה אני רוצה לפרסם כחדש.
ואז הוא לא מאפשר שמירה ומודיע כי לא השתנה השם. כאילו הוא כבר קליפ קיים.
בקיצור, יש לאפשר פרסום קליפ חדש כחדש ולא כעדכון קיים גם אם הקובץ נשמר לפני כן.
קליפ נחשב קיים רק אם כבר פורסם.

**Comment by natan1957** [comment]
![image](https://cloud.githubusercontent.com/assets/6491631/4021146/36efa0fe-2ae3-11e4-9756-7237f80a4a3d.png)

**Comment by natan1957** [comment]
נמצא ב 138
