### ISSUE TITLE
תצוגה לאחר עריכת סאונד

### ISSUE THREAD

**Issue by natan1957** [ariel1974/mymentor#136]
כשאני בוחר ומוחק קטע סאונד, במצב זום, אחרי שהמחיקה מתבצעת, התצוגה צאיכה לחזור לאותו הזום וכשהסמן נמצא בחלון התצוגה. אפשר באמצע.
כיום הזום מתבטל והסמן קופץ לתחילת הקובץ.

יש לוודא שזה מתנהג כך גם המצה הדבקה של קטע אאודיו לתוך הקובץ.

**Comment by ariel1974** [comment]
התנהגות ברירת מחדל של הרכיב. אפשרות להתערב תהיה כרוכה בשעת פיתוח

**Comment by natan1957** [comment]
כפי הנראה כתוצאה מהשינוי (ואולי לא), כשאני פותח קובץ סאונד הוא לא מוצג בחלון אלא לאחר שאני לוחץ על זום.
כך גם במקרה של אן-דו. זה לא היה קודם.

במקרה של בחירה ומחיקה או גזירה, הבחירה צריכה להתבטל והסמן צריך לעמוד בנקודת הגזירה. כיום הבחירה לא מתבטלת.

**Comment by natan1957** [comment]
התופעה האחרונה תוקנה.
בנוגע להתנהגות המקורית, בהעתקה והדבקה זה שומר על המיקום והזום.
בסימון ומחיקה (דל) זה מאבד את הזום ומציג את כל הקובץ.
יש לוודא שזה לא מאבד את הזום ואת המיקום של הסמן בכל בפעולות על הקובץ
