### ISSUE TITLE
התאמת שם השיעור לשפה לא עברית

### ISSUE THREAD

**Issue by natan1957** [ariel1974/mymentor#137]
אם נרשם טקסט לא עברי (אפשר לבדוק לפי האות הראשונה) בשדה תוספת לשם שיעור או בתיאור שיעור
 יש להשתמש בטמפלטים האנגליים במקום בעבריים לשם יצירת שמות השיעורים.ב
name_he_il , portalNamePart1_he_il ,  portalNamePart2_he_il

השינוי בא לדאוג לכך שאם המורה לא כותב בעברית, שם השיעור לא יופיע בעברית אלא באנגלית בתוספת השפה שלו.
בדרך כלל הוא יעשה את זה דרך הממשק האנגלי אבל החוקיות תקפה גם בממשק העברי

**Comment by ariel1974** [comment]
שעת פיתוח

**Comment by natan1957** [comment]
בממשק העברי, במקרה של שימוש בטמפלט אנגלי, הטקסט הידני שמשתלב בתוכו צריך להילקח מהשדה תוספת לשם שיעור ולא מהשדה תוספת לשם שיעור באנגלית

**Comment by ariel1974** [comment]
אני מבולבל...תסביר לי שוב לאט ובפירוט יותר
"מה ז"א "במקרה של שימוש בטמפלט אנגלי

**Comment by natan1957** [comment]
במקרה של שימוש בטמפלט אנגלי ז"א  במקום שימוש בטמפלט עברי וזה קורה  כאשר אתה מוצא שבתוספת לשם שיעור, או בתיאור שיעור נכתב טקסט לא עברי.
במקרה זה, כאמור יש להשתמש בטמפלט האנגלי כפי שאתה אכן עושה לשם אכלוס שם השיעור העברי.
התיקון הנדרש הוא, שבמקרה זה, צריך להכניס לטמפלט את השדה תוספת לשם שיעור העברי(שיש בו כרגע תוכן לא עברי) ולא את השדה תוספת לשם שיעור האנגלי.

כל זה כאמור עבור אכלוס של השיעור העברי.
שם השיעור האנגלי מתאכלס כרגיל.

**Comment by natan1957** [comment]
לא טופל.
התמונה הבאה אולי תסביר את השינוי הנדרש.
![image](https://cloud.githubusercontent.com/assets/6491631/4021085/4a7fa108-2ae0-11e4-9e18-a5c5a76fbae0.png)
