### ISSUE TITLE
מחיקת קובץ ישן בזמן שמירת חדש

### ISSUE THREAD

**Issue by natan1957** [ariel1974/mymentor#138]
כאשר אני פותח שיעור קיים, עושה שינוי ושומר כחדש, מוקם קליפ חדש וזה טוב, אבל הקובץ הישן במחשב נמחק ובמקומו נשמר החדש.
זה לא טוב. במקרה של שמירת חדש, אין למחוק את הישן. ,

**Comment by natan1957** [comment]
זה אמנם תוקן, אבל בעדכון שיעור קיים , כאשר משתנה לו השם, יש למחוק את הקודם כי כבר יש חדש במקומו.
זה עבד קודם נכון אבל עכשיו זה שובש.

**Comment by ariel1974** [comment]
אז הצלחת לבלבל אותי לגמרי. למעלה ביקשת לא למחוק, למטה ביקשת להחזיר את זה

**Comment by natan1957** [comment]
נכון, כי אלה מקרים שונים.
קיימות שלוש אפשרויות: הקמת שיעור חדש חדש, עדכון שיעור קיים, והקמת שיעור חדש המבוסס על שיעור קיים.

שיעור חדש חדש:
שיעור חדש חדש הוא שיעור שנבנה מאפס ולא משעור קיים.
במקרה כזה, הכפתור "עדכן שיעור קיים" לא פעיל
בתהליך בניית השיעור אני מבצע שמירות ביניים לפני הפרסום.
אני עושה זאת דרך לשונית פרסום. אני ממלא את הקטגוריות כדי לייצר את השם הסופי של השיעור ומבצע שמירת שיעור .
אני יכול לעשות שמירת ע"י התפריט או ע"י כפתור פרסום אבל לא לפרסם.
אבל, כאשר אני רוצה לפרסם, הוא נותן הודעת שגיאה ששם הקובץ לא השמנה.
ההודעה הזאת לא שייכת למקרה הזה אלא למקרה של פרסום שיעור חדש מתוך שיעור קיים.
לכן, במקרה זה יש לאפשר שמירת הקובץ למרות שלא השתנה השם שלו.
רק כדי להשלים את המקרה, אם תוך כדי שמירות הביניים או בשמירה במהלך הפרסום, אני משנה את שם השיעור, צריך לשמור את הקובץ עם השם החדש ולמחוק את הקובץ עם השם הישן.

עדכון שיעור קיים:
במקרה זה, אם אני משנה את שם הקובץ יש לשמור את החדש ולמחוק את הישן.

הקמת שיעור חדש מתוך שיעור קיים:
במקרה זה אני פותח את קליפ א, מבצע שינויים ומבקש לשמור כקליפ ב.
במקרה זה יש לשמור את קובץ ב עם השם החדש ולהשאיר את קובץ א כי הוא שייך לקליפ א שלא השתנה.
במקרה זה, שם הקובץ של קליפ ב חייב להיות שונה ואשר של קליפ א ואם הוא לא שונה, יש להציג הודעת שגיאה.

**Comment by natan1957** [comment]
בעדכון שיעור קיים הכולל שינוי בשם שיעור, הוא לא מוחק את הקובץ הישן 
בשמירת ביניים של שיעור הכולל שינוי שם שיעור הוא לא מוחק את הקובץ הישן

**Comment by natan1957** [comment]
![image](https://cloud.githubusercontent.com/assets/6491631/7536317/7ea5ac34-f597-11e4-8bd1-c1257bdf21f9.png)

**Comment by ariel1974** [comment]
שלח לי שיעור + יוז קייס כדי לשחזר את התקלה
