### ISSUE TITLE
עדכון קליפ שהקובץ שלו נמחק

### ISSUE THREAD

**Issue by natan1957** [ariel1974/mymentor#139]
האם במקרה של מחיקת הקובץ במחשב, יש יכולת לעדכן את הקליפ שלו?
איך ?

**Comment by ariel1974** [comment]
איזה מחיקה של איזה קובץ ? אני צריך יותר פרטים כדי לענות

**Comment by natan1957** [comment]
mmnt

**Comment by ariel1974** [comment]
תוכל לעדכן את הפרטים מתוך רשומת הקליפ
אבל כמובן לא תוכל ליצור קובץ mmnt ממנו

**Comment by ariel1974** [comment]
לעדכן את הקליפ במובן של לערוך את האודיו? 
בטח שלא...אולי רק להחליף אותו...

**Comment by natan1957** [comment]
אז יש פה בעיה. אני ביקשתי שהבאת קליפ קיים לסטודיו לשם עדכון יהיה מהטבלה. מהענן. אתה שכנעת אותי לשמור במחשב.  ואז החלה הסאגה של הצפנות וכו׳. 
המשמעות של מה שאתה אומר היא שאם הלך למשתמש הדיסק, הוא לא יוכל לעדכן שום קליפ. זה נראה לך פתרון נכון? 

נשלח מה-iPhone שלי

ב-Aug 22, 2014, בשעה 13:57, Ariel Illouz notifications@github.com כתב/ה:

**Comment by ariel1974** [comment]
מישהו פעם דיבר על זה שדבר כזה נדרש ? שחזור קבצי קליפ מהענן ? ממש לא.
תחשוב על מפתח תוכנה שמחזיק בקוד המקור אצלו במחשב ומפרסם את הקוד המקומפל לענן. בדיוק אותו דבר.

**Comment by natan1957** [comment]
אל תשווה מפתח תוכנה למשתמש.
אין דמיון בינהם.
להלן קטע מהאפיון המקורי,, אתה שכנעת אותי שהשמירה תהיה בדיסק ולטובת זה הוספת את ענין ההצפנה.
אז הוספתי גם את זה לאפיון.
באותו הזמן לא הייתי מודע שלמעשה, אם נמחק למשתמש הקובץ, אין לו יותר גישה לקליפ.
כמובן שאם השמירה הייתה בענן, הבעיה לא הייתה עולה...
שמירה זמנית על הדיסק כדי לזרז את העבודה זה בסדר.. אבל להתבסס על הדיסק של המשתמש זו לפי דעתי טעות, ומן הראוי היה, עם פרסום הקליפ, להעלות גם את קובץ המקור למקום בטח...
![image](https://cloud.githubusercontent.com/assets/6491631/4104862/4cf629a0-319a-11e4-8f19-f869667fbb78.png)

**Comment by ariel1974** [comment]
אין שום בעיה, אעלה לך את הקובץ לשדה ייעודי בענן, אבל שים לב שאני לא נכנס לענייני שחזורים. השחזור יתבצע ידנית מול הפארס

**Comment by natan1957** [comment]
ברור... השחזור ידני.  
השאלה האם להוסיף שדה לקליפ או להקים טבלה יעודית לגיבויים...
יש להעלות גם את קובץ האודיו?

נשלח מה-iPhone שלי

ב-Sep 1, 2014, בשעה 9:30, Ariel Illouz notifications@github.com כתב/ה:

**Comment by ariel1974** [comment]
שדה ברשומה. אל תעלה את קובץ האודיו - למיטב זכרוני הוא כבר שם

2014-09-01 10:18 GMT+03:00 natan1957 notifications@github.com:

> ברור... השחזור ידני.
> השאלה האם להוסיף שדה לקליפ או להקים טבלה יעודית לגיבויים...
> יש להעלות גם את קובץ האודיו?
> 
> נשלח מה-iPhone שלי
> 
> ב-Sep 1, 2014, בשעה 9:30, Ariel Illouz notifications@github.com כתב/ה:
> 
> > אין שום בעיה, אעלה לך את הקובץ לשדה ייעודי בענן, אבל שים לב שאני לא נכנס
> > לענייני שחזורים. השחזור יתבצע ידנית מול הפארס
> > 
> > —
> > Reply to this email directly or view it on GitHub.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ariel1974/mymentor/issues/139#issuecomment-54028322.

## 

Thanks,
Ariel

**Comment by natan1957** [comment]
זו אחת השאלות שלא קיבלתי תשובה...
שיניתי את שם קובץ האודיו ופתחתי את הקליפ בסטודיו. הוא נפתח ללא סאונד...

נשלח מה-iPhone שלי

ב-Sep 1, 2014, בשעה 10:20, Ariel Illouz notifications@github.com כתב/ה:

**Comment by natan1957** [comment]
בקשר לזה, וכדי לחסוך מקום,
ביקשתי מזמן להקטין את הקובץ שהסטודיו מייצר ל 64kbps ולוודא שהוא מונו ולא
סטריאו.

נתן.

2014-09-01 10:23 GMT+03:00 Natan nhelfman@gmail.com:

**Comment by ariel1974** [comment]
הוא נפתח ללא סאונד כי השם צריך להתאים בדיוק לשם הקובץ. משמע שם הקובץ שלך 
xxxxx.mnnx
xxxxx.mp3

**Comment by natan1957** [comment]
הבנתי את זה. אבל זה אומר שזה קובץ הסאונד הנדרש לפתיחת הקליפ ולכן יש לגבות גם אותו. 

נשלח מה-iPhone שלי

ב-Sep 1, 2014, בשעה 16:52, Ariel Illouz notifications@github.com כתב/ה:

**Comment by ariel1974** [comment]
כל העלאה כזו תדרוש זמן נוסף בפרסום. למה אתה רוצה להעלות את הקובץ שוב לא
הבנתי ?

2014-09-01 17:20 GMT+03:00 natan1957 notifications@github.com:

> הבנתי את זה. אבל זה אומר שזה קובץ הסאונד הנדרש לפתיחת הקליפ ולכן יש לגבות
> גם אותו.
> 
> נשלח מה-iPhone שלי
> 
> ב-Sep 1, 2014, בשעה 16:52, Ariel Illouz notifications@github.com כתב/ה:
> 
> > הוא נפתח ללא סאונד כי השם צריך להתאים בדיוק לשם הקובץ. משמע שם הקובץ שלך
> > xxxxx.mnnx
> > xxxxx.mp3
> > 
> > —
> > Reply to this email directly or view it on GitHub.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ariel1974/mymentor/issues/139#issuecomment-54065051.

## 

Thanks,
Ariel

**Comment by natan1957** [comment]
אם זה קובץ שיושב במחשב של המורה ונחוץ כדי לפתוח את הקליפ בסטודיו, אז מה שווה הגיבוי של mmnt בלי הגיבוי של mp3 ?

נשלח מה-iPhone שלי

ב-Sep 1, 2014, בשעה 17:22, Ariel Illouz notifications@github.com כתב/ה:

**Comment by natan1957** [comment]
יש לך רעיון אחר?

נשלח מה-iPhone שלי

ב-Sep 1, 2014, בשעה 17:22, Ariel Illouz notifications@github.com כתב/ה:

**Comment by natan1957** [comment]
במילים אחרות, קובץ הסאונד היחיד הקיים ברשומה באופן גלוי ושניתן להורדה הוא קובץ הפרוויו.
קובץ הסאונד המלא ארוז כפי הנראה בתוך קובץ אם אם אנ.

**Comment by ariel1974** [comment]
קובץ הסאונד המלא מקווץ וכולה לתוך השדה clipFile

**Comment by natan1957** [comment]
אני לא מבין. בשדה 
clipFile
יש קובץ
mmn
איפה הגיבוי של 
mmnt ?

**Comment by natan1957** [comment]
סוכם שבזמן פרסום אתה מעלה את הקובץ 
MMNT
לרשומת הקליפ. איפה הקובץ ?

**Comment by ariel1974** [comment]
למה להעלות את ה-mmnt לקליפ? 
זה קובץ המקור, למה אתה רוצה את זה שם ? מי ימשוך את זה משם ?

**Comment by natan1957** [comment]
זה נועד לאפשר למשתמש שמחק בטעות את קובץ המקור או שהדיסק שלו קרס וכו' לקבל
חזרה את קבצי המקור כדי לעדכן קליפ קיים.
ברור שהוא לא יעשה את זה לבד אלא בעזרתי.
קובץ הסאונד נמצא בתוך קובץ הקליפ  ואילו קובץ המקור MMNT לא קיים.
לכן יש צורך להעלות אותו לרשומת הקליפ שיישמר שם למקרה של שחזור.
באפיון המקורי הדרישה הייתה לא לשמור כלום על הדיסק המקומי אלא רק ב parse.
מסיבות של גיבוי ומניעת אפשרות ההעברה ממשתמש למשתמש.
אתה בחרת לשמור בדיסק  ולמנוע העברה בדרך אחרת. עכשיו חסר העניין של הגיבוי
וזה הפתרון.

2015-05-16 20:34 GMT+03:00 Ariel Illouz notifications@github.com:

**Comment by ariel1974** [comment]
נוצר שדה חדש mmntFile
שם תמצא את הקובץ
