### ISSUE TITLE
הצגת קטגוריה פרשה

### ISSUE THREAD

**Issue by natan1957** [ariel1974/mymentor#14]
בחיפוש מקור, הקטגוריה פרשה מוצגת גם אם לא משויכת לעולם תורה.
יש לוודא שהכול מסונן לפי העולם

**Comment by natan1957** [comment]
לא ראיתי שיוך בקטגוריה1 לעולם תוכן. אין עמודה כזאת.

**Comment by ariel1974** [comment]
![image](https://f.cloud.github.com/assets/3278964/2058205/f3d8547e-8b63-11e3-9fb5-50cbfabf7afe.png)

**Comment by natan1957** [comment]
כל הפרשות של  ויקרא לא משוייכות כעת לעולם תוכן.
ובכל זאת מופיעות ברשימה.
האם אתה בודק את זה, או מסתפק שהקטגוריה הראשית משוייכת ?

![image](https://f.cloud.github.com/assets/6491631/2058725/82cab214-8b80-11e3-8b53-abd23ce7fd07.png)

**Comment by ariel1974** [comment]
רק לפי הקשר בין קטגוריה 1 ל-2
תוודא שהנתונים נכונים

**Comment by ariel1974** [comment]
זה טופל
