### ISSUE TITLE
טיפול בקובץ הפרוויו

### ISSUE THREAD

**Issue by natan1957** [ariel1974/mymentor#140]
בעדכון שם קובץ, גם קובץ הסאונד מתעדכן אבל קובץ ה פרוויו לא
יש להקפיד שקובץ הפרוויו יטופל בכל המקרים שקוהץ הסאונד מטופל.

**Comment by ariel1974** [comment]
הפריוויו זה סתם קובץ שמתחדש כל פרסום
אם זה ממש מפריע אני אמחק אותו אחרי כל פרסום

**Comment by natan1957** [comment]
תתיחס לשאלה שלי בנוגע לקובץ המלא.
