### ISSUE TITLE
שמירת קובץ הסאונד

### ISSUE THREAD

**Issue by natan1957** [ariel1974/mymentor#141]
בביצוע שמירה מהתפריט, קובץ הסאונד נשמר יחד עם ה אמ אמ אנ טי.
בשמירת  הקובץ במהלך פרסום, קובץ הסאונד לא נשמר והוא כולל את הגרסה הקודמת של לפני העריכה והשמירה.

לא ברור מתי נשמר קובץ פרוויו

**Comment by ariel1974** [comment]
אני לא מבין את הבעיה....במהלך הפרסום מתבצעים מספר פעולות מאחורי הקלעים כמו יצירת פריווי וכאלה
מה זה חשוב ?

**Comment by natan1957** [comment]
אני מבין שלמעשה לקובץ הסאונד אין תפקיד. ניתן אפילו למחוק אותו, שכן הוא נמצא בתוך קובץ
mmnt
תאשר לי שזה נכון.

ניסיתי לפתוח אם הסיסמה את הקובץ 
mmnt
ומצאתי בתוכו עוד אחד כזה. האם ניתן לראות מה יש בתוכו שלא באמצעות הסטודיו ?

**Comment by ariel1974** [comment]
ממש לא, הקובץ עולה ישירות לשדה ייעודי ברשומת הקליפ

**Comment by natan1957** [comment]
ז"א שלקובץ הסאונד יש תפקיד, הוא נטען לסטודיו יחד עם ה אמ.אמ.אנ.טי, ולמעשה אסור למחוק אותו...
