### ISSUE TITLE
מחיר תמיכה

### ISSUE THREAD

**Issue by natan1957** [ariel1974/mymentor#142]
שדה שהתפספס, יש להוסיף שדה מחיר תמיכה ליד מחיר.
ליד השדה יש להציג את מטבע ברירת המחדל מרשומת המשתמש.

**Comment by ariel1974** [comment]
שעת פיתוח - אנא אשר

**Comment by natan1957** [comment]
מאשר.

קח בחשבון שממתינה לך עדיין פעילות של התייחסות למטבע ולשער,  שכלולה בפיתוח המערכת ושעדיין ממתינה לטיפול בטבלת השערים ע"י תום.
הפעילות תתיחס גם למחיר שיעור וגם למחיר תמיכה שמתווסף עכשיו

**Comment by ariel1974** [comment]
נתן כבר סיכמנו שהתכולה המקורית באפיון הראשון ששלחת כבר לא קשורה לאיך שהסטודיו נראה היום
אז לומר שאיזשהי פונקציה כלולה בפנים...נו באמת...יש מלא דברים שקיבלת שלא אופיינו ולא קיבלתי עליהם תמורה
מבחינתי כבר נמתח קו מזמן - כל שינוי חדש יתומחר - כל באג כמובן יטופל ללא עלות

לגבי השינוי הנדרש - ציין לאיזה שדה להתייחס לכל אחד מהשדות שיהיה ברור לכולם

**Comment by natan1957** [comment]
כן, ההבדל היחיד הוא, שעד ביקשת את יתרת התשלום, הנושא הזה היה עדיין פתוח וסיכמנו שתשלים אותו כשעניין המטבעות יהיה מוכן. 

אשלח לך את שם השדה כשאהיה בבית. 

נשלח מה-iPhone שלי

ב-Aug 22, 2014, בשעה 13:55, Ariel Illouz notifications@github.com כתב/ה:

**Comment by ariel1974** [comment]
אוקי ...שלח את השדות - אם אני מבין נכון
פשוט לשתול לייבל עם סימון המטבע בצמוד לשדות ללא אפשרות עריכה - נכון ?

**Comment by ariel1974** [comment]
מחיר תמיכה ניתן לעריכה ? אם כן - זה שדה שנמצא בטבלת משתמשים או קליפים ?

**Comment by ariel1974** [comment]
יש את זה ברמת הקליפ

![image](https://cloud.githubusercontent.com/assets/3278964/4010059/a98825d2-29ee-11e4-89cc-253f5c96b10b.png)

ויש את זה למשתמש

![image](https://cloud.githubusercontent.com/assets/3278964/4010065/c6bfda96-29ee-11e4-9c34-bd287396c47a.png)

**Comment by natan1957** [comment]
ברמת הקליפ. ניתן לעריכה, המורה שמקים/מעדכן קליפ מקליד אותו. סוג המטבע נלקח מרשומת המשתמש. 
בהמשך(בטיפול במטבעות) הערך יתורגם מטבלת שערים. 

נשלח מה-iPhone שלי

ב-Aug 22, 2014, בשעה 14:23, Ariel Illouz notifications@github.com כתב/ה:

**Comment by ariel1974** [comment]
סוג המטבע הוא לייבל - לא ניתן לעריכה

**Comment by ariel1974** [comment]
טופל - אנחנו ביתרה של 4 שעות לידיעתך

**Comment by natan1957** [comment]
השדה צריך להיות "מחיר תמיכה מרחוק". זה לא מחיר השיעור עם תמיכה אלא מחיר התמיכה בלבד. השדה לא אמור להיבדק מול המינימום, הוא גם יכול להישאר ריק.
