### ISSUE TITLE
פנייה מתום בנוגע להרשאת מנהל לשיעורים

### ISSUE THREAD

**Issue by natan1957** [ariel1974/mymentor#144]
מייל שנשלח אליך מתום ב 14/8
![image](https://cloud.githubusercontent.com/assets/6491631/3905883/33597c42-22ed-11e4-864b-991bbede7c13.png)

**Comment by ariel1974** [comment]
שעת פיתוח - אנא אשר

**Comment by natan1957** [comment]
מאשר

**Comment by ariel1974** [comment]
זה כבר טופל
