### ISSUE TITLE
הודעה על חוסר הרשאה

### ISSUE THREAD

**Issue by natan1957** [ariel1974/mymentor#145]
הודעה זו מוצגת לתלמיד שמנסה להשתמש בסטודיו
האם ההודעה מופיעה גם מסיבות אחרות ? אני מניח שכן.
ההודעה צריכה להיות בשפת הממשק ולהתייחס לסיבה...
אחרת יהיה בלתי אפשרי  לתת מענה למשתמש שיתלונן שהוא מקבל הודעה כזו.
![image](https://cloud.githubusercontent.com/assets/6491631/4008228/10980e9c-29d4-11e4-9e58-fbc5d34e8469.png)

**Comment by ariel1974** [comment]
כשתלמיד מנסה לפתוח את הסטודיו
