### ISSUE TITLE
משך הקליפ

### ISSUE THREAD

**Issue by natan1957** [ariel1974/mymentor#147]
כיום יש ברשומה גודל הקליפ, נא הוסף גם את משך הקליפ בדקות ושניות.

**Comment by ariel1974** [comment]
שעת פיתוח נא אשר, ולאיזה שדה זה הולך ? שדה חדש?

**Comment by ariel1974** [comment]
יצרתי שדה clipDuration 
לא ממתין לאישורך חייב לסיים להיום כבר מעלה גרסה
אנחנו עומדים על 5 שעות חוב
שבת שלום

**Comment by ariel1974** [comment]
![image](https://cloud.githubusercontent.com/assets/3278964/4087673/d7821a66-2f51-11e4-940a-d7dfa33748fe.png)
