### ISSUE TITLE
טיפול במטבעות

### ISSUE THREAD

**Issue by natan1957** [ariel1974/mymentor#149]
להלן תמצית רלוונטית מתוך מסמך  אופן הטיפול במטבעות שנמצא בדרופ בוקס

בסיס הנתונים כולל טבלת מטבעות
 Currency 
טבלת המטבעות כוללת את המטבעות הנתמכים, את שער ההמרה (ביחס לדולר) האחרון הידוע ואת תאריך השער.

הסטודיו מקבל את המטבע של המורה מרשומת המורה ומציג אותו.
מחיר המינימום לכל סוג שיעור נמצא בטבלת קטגוריה3 בשקלים. יש לחשב ולהציג את הסכום במטבע של המורה לפי יחס ההמרה מטבלת המטבעות.
המורה מפרסם מחיר שיעור ומחיר תמיכה. הסכומים נרשמים ברשומת השיעור במטבע של המורה. בנוסף נרשם גם המטבע.
אם המורה פותח בסטודיו קובץ שנרשמו בו מחירים, יש לבדוק את המטבע שלהם. אם זהה למטבע הנוכחי של המורה, יש להציג את הערך הקיים. אם שונה מהמטבע הנוכחי, יש לתרגם ולהציג לפי המטבע הנוכחי. בשמירת הקובץ יש לרשום את הסכום במטבע הנוכחי. ואת סוג המטבע

**Comment by ariel1974** [comment]
מה ז"א שורה 4 "ביחס לדולר" ? 
זה ביחס לשקל

![image](https://cloud.githubusercontent.com/assets/3278964/5560907/7e86d14e-8dbc-11e4-8f44-48b1b328e190.png)

**Comment by ariel1974** [comment]
http://www.webservicex.net/currencyconvertor.asmx?op=ConversionRate

**Comment by natan1957** [comment]
בשמירת קליפ הוא בודק מול מחיר מינימום שקלי למרות שמציג את התרגום הדולרי

 בעדכון קליפ שנשמר במקור בשקלים אבל עכשיו המורה עבר לדולר, הערכים שהיו מוצגים מתורגמים לדולר באופן תקין. בזמן עדכון הקליפ, הערכים הדולריים נשמרים (זה תקין) אבל סוג המטבע לא נרשם דולרי אלא נשאר שקלי.
![image](https://cloud.githubusercontent.com/assets/6491631/7665894/1c3f82b0-fbd5-11e4-9d07-63eb193303fe.png)
![image](https://cloud.githubusercontent.com/assets/6491631/7665889/ddccee14-fbd4-11e4-9e6f-dfc3eddd62f0.png)

**Comment by ariel1974** [comment]
אחרי השינוי של המטבע למורה פתחת מחדש את המערכת ?

**Comment by natan1957** [comment]
כן.
אתה יכול לראות בתמונה שהמטבע המוצג הוא דולר.

**Comment by ariel1974** [comment]
תספק לי שם משתמש סיסמה ויוז קייס

**Comment by natan1957** [comment]
אני שולח לך קובצי מקור, המחיר שנשמר הוא 50 דולר
בקבצים נשמרו ע"י 
more33@gmail.com pw= more33
בזמן שנשמרו מטבע המורה היה דולר.
עכשיו מטבע המורה שקל.
אם תפתח את הקובץ יוצג 200 שקל. זה נכון.
אבל אם תשנה קצת את השם ותבצע שמירת חדש, תוכל לראות בטבלת הקליפים שנשמר הערך 200 אבל במטבע דולר.
אם תקיש בסטודיו חדש ותפתח את הקובץ שנשמר יוצג לך 800 שקל

**Comment by ariel1974** [comment]
הוספתי בודעה מתאימה ועדכנתי את מטסע הקליפ להיות מטבע המורה
