### ISSUE TITLE
מיון קטגוריה פרשה

### ISSUE THREAD

**Issue by natan1957** [ariel1974/mymentor#15]
בחיפוש מקור בהצגת פרשות של דברים, הפרשה שפטים מוצגת ראשונה למרות ששדה המיון אומר לה להיות חמישית

**Comment by ariel1974** [comment]
לא נכון, המיון תקין

![image](https://f.cloud.github.com/assets/3278964/2048730/e9c3e67e-8a50-11e3-939b-c3a56c7f7cb2.png)
