### ISSUE TITLE
להוסיף לוגו

### ISSUE THREAD

**Issue by natan1957** [ariel1974/mymentor#150]
![image](https://cloud.githubusercontent.com/assets/6491631/5103256/5084bbea-6fde-11e4-83cf-ba55b5dae298.png)

לסלק את כפתור הפאוז

להחליף את כפתור הפליי לכפתור לא מפוקסל
![image](https://cloud.githubusercontent.com/assets/6491631/5126548/82be553c-70d6-11e4-8897-a47ce39e328a.png)

**Comment by ariel1974** [comment]
שלח לוגו פורמט png

**Comment by natan1957** [comment]
טעות שלי.. תעביר את הלוגו לכותרת כך שיופיע בכל מצב, לא רק בלשונית טקסט..
שים לב לממשק האנגלי..
