### ISSUE TITLE
שינוי ברשומת המשתמש

### ISSUE THREAD

**Issue by natan1957** [ariel1974/mymentor#153]
חלק משדות המשתמש פוצלו לטבלה נפרדת בשם
UserAdminData
ניתן להגיע אליה בעזרת שדה פוינטר
userData
ברשומת המשתמש

שלושה שדות רלוונטים לסטודיו שהועברו לרשומה זו הם
userPublishingStatus   userStatus   userRole

השדה
userRole
מספק את האינדיקציה האם המשתמש מורה תלמיד או מנהל על פי הערכים. למורה ולמנהל מותר להפעיל את הסטודיו.
students  teachers administrators
וזה מחליף לפי דעתי את השדה
userType

יש לוודא שרק משתמש מסוג "מורה" או "מנהל" בסטטוס משתמש "פעיל" יכול להפעיל את בסטודיו

**Comment by ariel1974** [comment]
טוב...כאן יש שעתיים כולל הבדיקות שיגררו השינויים הללו - זה לגמרי חדש. על הבאג השני כמובן אני לא מחייב.
יאללה תאשר ואתחיל פיתוח

**Comment by natan1957** [comment]
טוב. אבל תבדוק.. אולי זה ייצא רק שעה.. זה בסך הכל אחזור עוד רשומה והזזת ההתייחסות של שלושה שדות..
תמדוד...

**Comment by natan1957** [comment]
בנוגע להרשאת שימוש בסטודיו, יש להוסיף גם בדיקה שסטטוס פרסום שיעור שווה ל פעיל או  או ל טעון אישור.
לבעלי סטטוס אחר (נכון לעכשיו חסום אבל ייתכנו עוד) אין הרשאה לסטודיו.

תכל'ס, כמה זמן לקח...

**Comment by ariel1974** [comment]
יותר משעתיים - קבלת הנחה.

**Comment by natan1957** [comment]
עכשיו אף משתמש לא מצליח להיכנס.
מתקבלת הודעה משתמש לא מורשה

**Comment by ariel1974** [comment]
לא רלוונטי
