### ISSUE TITLE
חסר בהתקנה קובץ סאונד

### ISSUE THREAD

**Issue by natan1957** [ariel1974/mymentor#156]
לאור קריסתו של מחשבי, עברתי לעבוד על מחשב אחר.
לאחר ההתקנה של הסטודיו ועם ההפעלה קיבלתי את ההודעה הזאת
![image](https://cloud.githubusercontent.com/assets/6491631/5453936/edecd456-84df-11e4-90df-3f7a20d9a9a0.png)
ומיד לאחר מכן את ההודעה
![image](https://cloud.githubusercontent.com/assets/6491631/5453950/333cf1bc-84e0-11e4-8747-b2ca5e7ac0a7.png)

בהמשך שמתי לב שהקובץ קיים אבל הסטודיו לא מסוגל לטעון קובץ סאונד
כנראה בגלל ההודעה השנייה שקשורה לפרמטר

**Comment by ariel1974** [comment]
זו לא תקלה - בגלל גרסת המפתחים
