### ISSUE TITLE
שמירת חדש

### ISSUE THREAD

**Issue by natan1957** [ariel1974/mymentor#161]
שמירת חדש צריכה לבדוק ששם הקליפ השתנה ושלא קיים כזה קליפ
שמירת חדש צריכה גם לשמור קבצי קליפ חדשים
שני הדברים לא קורים

**Comment by natan1957** [comment]
בשמירת חדש מקיים, יש לבצע את הבדיקה שלא קיים כזה ולמנוע דריסתו.
שולח סרטון שמראה שניתן להקים קליפ עם אותו השם

**Comment by ariel1974** [comment]
ממתי סיכמנו למנוע דריסתו...אני לא זוכר כזה דבר
אני פשוט מקפיץ את ה"שמירה בשם" - המשתמש יכול לדרוס אותו
אני לא מנעתי את זה בעבר

**Comment by natan1957** [comment]
לא זוכר ממתי, אבל ממזמן... זה חלק מהוספת הכפתור ״שמור כחדש״. 
גם כפתור עדכן קיים לא מתפקד נכון, בעדכון שם קליפ יש לשמור את הקבצים בשם החדש ולמחוק את הקבצים עם השם הישן. 

נשלח מה-iPhone שלי

ב-Apr 11, 2015, בשעה 18:58, Ariel Illouz notifications@github.com כתב/ה:
