### ISSUE TITLE
תרגום ובדיקת מחיר מינימום

### ISSUE THREAD

**Issue by natan1957** [ariel1974/mymentor#166]
מחיר מינימום של עליה ראשונה 90 ש"ח. שער הדולר 3.45 ש"ח. מחיר מינימום דולרי צריך להיות  26. ולא  22 וחצי.

כמו כן, אם אני רושם 30, הוא עדיין לא מאפשר. הוא מאפשר רק אם אני רושם 90 ומעלה. ז"א שהבדיקה היא לא מול התרגום אלא מול מחיר המקור השקלי.

![image](https://cloud.githubusercontent.com/assets/6491631/7105129/679a96fc-e111-11e4-9720-03931baa8674.png)

**Comment by ariel1974** [comment]
יצרתם טבלה חדשה בשם CurrencyExchangeRate
אני עבדתי מול הערך שנמצא בשדה זה

![image](https://cloud.githubusercontent.com/assets/3278964/7526836/4426aac8-f51e-11e4-860c-04334e827d6c.png)

לשינוי זה נדרש שעתיים פיתוח

**Comment by natan1957** [comment]
הטבלה שאתה עובד עליה היא הטבלה הנכונה.
היא מייצגת את השער הנוכחי.
כפי הנראה שיניתי בה את השערים כדי שיהיה נוח לחשב. אבל זה טבעי בשערים בה צריכים להתעדכן כל יום.
הטבלה השנייה שומרת היסטוריית שערים והיא לא רלוונטית.
עדיין יש לתקן את התופעה שבדיקת המינימום היא מול הערך השקלי ולא מול התרגום למטבע המשתמש.

**Comment by ariel1974** [comment]
תקנתי את בדיקת הערך
