### ISSUE TITLE
עיצוב דף פרסום באנגלית

### ISSUE THREAD

**Issue by natan1957** [ariel1974/mymentor#167]

**Comment by natan1957** [comment]
להחליף
Scheduling --> Timing
English teacher --> Englhsh name
לסדר את הבלאגן
להסתיר את מילות מפתח גם בעברית
לטפל בסטטוס בגרסה האנגלית
לשנות את האייקון בכותרת הדף
להוסיף חיווי עם שם המשתמש הפעיל

![image](https://cloud.githubusercontent.com/assets/6491631/7217162/947cbcf6-e623-11e4-9724-73d2ee82be59.png)

**Comment by natan1957** [comment]
בממשק העברי
להעלים את מילות מפתח
לשנות את שמות יחידות הלימוד ל: קטעים, משפטים, פסקאות, הכל
להעביר את הלוגו מלשונית הטקסט לאזור כותרת כללי
![image](https://cloud.githubusercontent.com/assets/6491631/7488295/ef3fa1c0-f3d0-11e4-8d33-d59615226a88.png)
![image](https://cloud.githubusercontent.com/assets/6491631/7488332/7b3db4dc-f3d1-11e4-9d9e-2ff8a5bd7234.png)

בממשק האנגלי
להעלים את מילות מפתח
להחליף scheduling ל Timing
לשנות את יחידות הלימוד ל:
Section, Sentence, Paragraph, All
לסדר את Minimum price
להוסיף את שם המשתמש
לטפל בהצגת רשימת הסטטוסים
להזיז את הלוגו מלשונית הטקסט לאזור כותרת כללית
![image](https://cloud.githubusercontent.com/assets/6491631/7488518/fdd11f7c-f3d3-11e4-81d4-07d6aca90a70.png)
![image](https://cloud.githubusercontent.com/assets/6491631/7488545/4fd56454-f3d4-11e4-8f4e-1e94ed674668.png)

**Comment by ariel1974** [comment]
בוצע
למעט האייקון - אין לי אחד כזה - שלח ואדביק

**Comment by natan1957** [comment]
הכותרת והשדה של מילות מפתח בעברית ובאנגלית לא הועלמו
הלוגו קטן להחריד. אין מצב להגדיל ?
יכול לגלוש לתוך שורת התפריט העליונה.
צריך הכי גדול שאפשר.
![image](https://cloud.githubusercontent.com/assets/6491631/7531272/75cf654c-f55f-11e4-93ba-d7bda03e2751.png)

**Comment by natan1957** [comment]
איזה אייקון חסר ?

**Comment by ariel1974** [comment]
לא ניתן להגדיל את הלוגו באיזור זה
רצית לשתול אייקון לחלונית

**Comment by natan1957** [comment]
שלחתי.
חפש איזה דרך להגדיל.
זה על הפנים וזה חשוב..

יש להעלים את מילות מפתח
