### ISSUE TITLE
טיפול בטקסט ללא טעמים

### ISSUE THREAD

**Issue by natan1957** [ariel1974/mymentor#17]
לדעתי חבל לייצר פרקים לא רלוונטיים בג'ייסון .
אם הטקסט המקורי לא כולל טעמים או לא כולל ניקוד או לא כולל את שנייהם, לא ראוי לייצר פרקים לא רלוונטיים.
חבל על המקום ועל האנרגייה.

**Comment by ariel1974** [comment]
לא עולה לאף אחד כלום ומדובר בבייטים בודדים
חבל לשנות את הסכימה עכשיו

**Comment by natan1957** [comment]
טוב.
