### ISSUE TITLE
אנטר לא מזוהה לסוף פסקה

### ISSUE THREAD

**Issue by natan1957** [ariel1974/mymentor#18]
![image](https://f.cloud.github.com/assets/6491631/2045565/c902e76a-89fa-11e3-86c2-8693ddb3c927.png)

**Comment by ariel1974** [comment]
אצלי זה תקין, כנראה זה משהו בטקסט, שלח לי אותו

![image](https://f.cloud.github.com/assets/3278964/2048753/e701a89e-8a51-11e3-813a-b1dff4de6e28.png)

**Comment by natan1957** [comment]
שים לב שכשהאנטר מופיע לבד הוא מזוהה. אבל במקרה שהאנטר בא אחרי נקודותיים הוא לא מזוהה. ייתכן ואתה קובע קודם את הפסקאות ואחר כך את המשפטים. ואז אתה דורס את העוגן האדום עם עוגן סגול.

![image](https://f.cloud.github.com/assets/6491631/2051213/56acda1e-8a85-11e3-897e-83dd741362a5.png)
