### ISSUE TITLE
סימון עוגנים ידני

### ISSUE THREAD

**Issue by natan1957** [ariel1974/mymentor#19]
יש לשנות את שיטת הסימון הידני של גבולות באופן הבא: ארבעת הגבולות ייוצגו ע"י ארבעה כפתורים לחיצים. לחיצה על כפתור מחליפה את מצבו ממשוחרר ללחוץ וההפך. כמו כן משחררת כפתור אחר שהיה לחוץ(אם היה). ברגע שכפתור (לדוגמה פסקה) לחוץ, הקלקה בטקסט מכניסה עוגן פסקה. הקלקה נוספת מבטלת את העוגן.

**Comment by ariel1974** [comment]
אני לא מבין - זה טופל מזמן

**Comment by natan1957** [comment]
זה טופל באופן חלקי. במיוחד בנוגע למחיקת עוגנים אבל לא בנוגע להכנסה ידנית של עוגנים. שים לב לחלק האחרון: ברגע שכפתור (לדוגמה פסקה) לחוץ, הקלקה בטקסט מכניסה עוגן פסקה. הקלקה נוספת מבטלת את העוגן.
זאת אומרת שכאשר כפתור ירוק לחוץ, הקלקה עם העכבר בטקבט קובעת שם עוגן. בשונה מהמצב היום בו כדי לקבוע עוגן יש למקם את הסמן בטקסט ולהקליק על הכפתור הירוק.
במילים אחרות, ברגע שהירוק לחוץ, ניתן להקליק שוב ושוב בטקסט ולהכניס עוגנים רבים.

**Comment by ariel1974** [comment]
נתן תכונה זו לא תוכננה בתכולה במקורית
אני לא מבצע אותה כעת - נסיים את התכולה עליה התחייבתי
ונפתח שושים בהמשך בפול חדש
