### ISSUE TITLE
חלוקה אוטומטית של מילים

### ISSUE THREAD

**Issue by natan1957** [ariel1974/mymentor#20]
יש להוסיף אפשרות לחלוקה אוטומטית של מילים(בדרך כלל זה יהיה לפי תו רווח). ברשימות התווים של שלושת החלוקות(פסקה משפט ומילים) יש להוסיף ברירת מחדל "ללא חלוקה".

**Comment by ariel1974** [comment]
ברשימות התווים של שלושת החלוקות(פסקה משפט ומילים) - למה אתה מתכוון ???
איפה ?

**Comment by natan1957** [comment]
חלוקה אוטומטית כיום, מכניסה עוגנים סגולים ואדומים. משפטים ופסקאות. אני מבקש את האפשרות להכניס אוטומטית גם  עוגנים ברמת מילים. זאת אומרת עוגנים צהובים. בדרך כלל התו המסמן סוף מילה הוא רווח. לכן יש להכניס רווח לרשימה. יש להתעלם כמובן מרווחים כפולים.

דבר שני, אחרי שאני בוחר לדוגמה נקודותיים, אין לי אפשרות לבטל את הבחירה. לכן ביקשתי להוסיף שורה ריקה או שורה או עם הטקסט בחר כדי שיהיה אפשר להתחרט.

**Comment by natan1957** [comment]
חלוקה למילים פועלת רק כשבוחרים "רווח" מהרשימה. אם רושמים תו מסויים, זה לא פועל.
