### ISSUE TITLE
ארגון מחדש של המסך

### ISSUE THREAD

**Issue by natan1957** [ariel1974/mymentor#27]
ראה במצגת שבדרופ בוקס

**Comment by ariel1974** [comment]
שים לינק

**Comment by natan1957** [comment]
https://www.dropbox.com/s/hejojj0yopwbpwp/%D7%A1%D7%98%D7%95%D7%93%D7%99%D7%95%20%D7%92%D7%A8%D7%A1%D7%94%202%2001.pptx

**Comment by natan1957** [comment]
![image](https://f.cloud.github.com/assets/6491631/2051461/c01157f6-8a89-11e3-8895-9e6ed5460f68.png)

![image](https://f.cloud.github.com/assets/6491631/2051473/e19c089e-8a89-11e3-85e2-220d0ce6ee1b.png)
