### ISSUE TITLE
חיווי עוצמת מיקרופון גם כשאין הקלטה

### ISSUE THREAD

**Issue by natan1957** [ariel1974/mymentor#30]
יש להציג את עוצמת ההקלטה בפס החיווי גם אם אין הקלטה ממש. אם המוצר לא ידע לעשות את זה, אתה יכול להגיד לו להקליט באינטרוולים של שלוש שניות ולדרוס כל הזמן את ההקלטות הקודמות, העיקר שיראה את חיווי העוצמה.

**Comment by ariel1974** [comment]
שלחתי שאילתא לסאפורט

**Comment by natan1957** [comment]
יש להוסיף את התכונה הזאת גם במסך הקלטה.
יש להוסיף למסך זה גם את פקד כוון עוצמת ההקלטה ולדאוג שיעבוד נכון.

**Comment by natan1957** [comment]
זה פועל בחלון בדיקה, זה לא פועל בחלון הקלטה.

 הפקדים עצמת הקלטה ועצמת שמע צריכים להיות מסונכרנים. עם המסכים האחרים.
כך שאם במסך בדיקת שמע אני מכוון אותם ועובר למסך הקלטה, לא צריך לשנות שוב.
וכך גם לגבי פקד עצמה במסך תזמון.
