### ISSUE TITLE
בדיקת השמעה בלבד

### ISSUE THREAD

**Issue by natan1957** [ariel1974/mymentor#33]
יש להוסיף כפתור שישמיע קובץ שמע של המערכת כדי לבדוק את הערכת ההשמעה ללא קשר להקלטה.

**Comment by ariel1974** [comment]
תעביר לי קובץ שמע

**Comment by natan1957** [comment]
שלחתי

**Comment by natan1957** [comment]
שלחתי קובץ ארוך, או שתאפשר עצירת השמעה (ע"י קליק נוסף) או שאשלח קובץ יותר קצר.
מה שתבחר...
