### ISSUE TITLE
הודעת שגיאה בניסיון למחוק עוגנים אדומים

### ISSUE THREAD

**Issue by natan1957** [ariel1974/mymentor#35]
![image](https://f.cloud.github.com/assets/6491631/2057307/dd491cec-8b1e-11e3-967a-e31763b0d4cc.png)

עיין בסופה של הודעה זו לקבלת פרטים אודות הפעלת 
איתור באגים בשיטת just-in-time (JIT) במקום תיבת דו-שיח זו.

*************\* טקסט החריג **************
System.ArgumentOutOfRangeException: הערך של '3443' אינו חוקי עבור 'start'. על 'start' להיות בין 0 ל- 3441.
שם פרמטר: start
   ב-  System.Windows.Forms.RichTextBox.Find(String str, Int32 start, Int32 end, RichTextBoxFinds options)
   ב-  System.Windows.Forms.RichTextBox.Find(String str, Int32 start, RichTextBoxFinds options)
   ב-  MyMentor.FormMain.RemoveAnchor(AnchorType type)
   ב-  MyMentor.FormMain.mnuAnchors_RemoveParagraphs_Click(Object sender, EventArgs e)
   ב-  MyMentor.FormMain.tbrRemoveAnchors_Click(Object sender, EventArgs e)
   ב-  System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   ב-  System.Windows.Forms.ToolStripButton.OnClick(EventArgs e)
   ב-  System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   ב-  System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   ב-  System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   ב-  System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   ב-  System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   ב-  System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   ב-  System.Windows.Forms.Control.WndProc(Message& m)
   ב-  System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   ב-  System.Windows.Forms.ToolStrip.WndProc(Message& m)
   ב-  System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   ב-  System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   ב-  System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

*************\* הרכבות שנטענו **************
mscorlib
   גירסת הרכבה: 4.0.0.0
   גירסת Win32: 4.0.30319.34003 built by: FX45W81RTMGDR
##    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll

MyMentor
   גירסת הרכבה: 7.3.0.0
   גירסת Win32: 7.3.0.0
##    CodeBase: file:///C:/Program%20Files%20(x86)/MyMentor%20Studio%20V2/MyMentor.exe

Parse
   גירסת הרכבה: 1.2.10.0
   גירסת Win32: 1.2.10.0
##    CodeBase: file:///C:/Program%20Files%20(x86)/MyMentor%20Studio%20V2/Parse.DLL

System.Runtime
   גירסת הרכבה: 4.0.0.0
   גירסת Win32: 4.0.30319.33440
##    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Runtime.dll

System.ObjectModel
   גירסת הרכבה: 4.0.0.0
   גירסת Win32: 4.0.30319.33440
##    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ObjectModel/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.ObjectModel.dll

System
   גירסת הרכבה: 4.0.0.0
   גירסת Win32: 4.0.30319.34003 built by: FX45W81RTMGDR
##    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll

System.Threading.Tasks
   גירסת הרכבה: 4.0.0.0
   גירסת Win32: 4.0.30319.33440
##    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Threading.Tasks/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Threading.Tasks.dll

System.Windows.Forms
   גירסת הרכבה: 4.0.0.0
   גירסת Win32: 4.0.30319.33440 built by: FX45W81RTMREL
##    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll

System.Drawing
   גירסת הרכבה: 4.0.0.0
   גירסת Win32: 4.0.30319.33440 built by: FX45W81RTMREL
##    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll

System.Collections
   גירסת הרכבה: 4.0.0.0
   גירסת Win32: 4.0.30319.33440
##    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Collections/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Collections.dll

System.Threading
   גירסת הרכבה: 4.0.0.0
   גירסת Win32: 4.0.30319.33440
##    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Threading/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Threading.dll

System.Core
   גירסת הרכבה: 4.0.0.0
   גירסת Win32: 4.0.30319.33440 built by: FX45W81RTMREL
##    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll

System.Reflection
   גירסת הרכבה: 4.0.0.0
   גירסת Win32: 4.0.30319.33440
##    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Reflection/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Reflection.dll

System.Reflection.Extensions
   גירסת הרכבה: 4.0.0.0
   גירסת Win32: 4.0.30319.33440
##    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Reflection.Extensions/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Reflection.Extensions.dll

Parse.NetFx45
   גירסת הרכבה: 1.2.10.0
   גירסת Win32: 1.2.10.0
##    CodeBase: file:///C:/Program%20Files%20(x86)/MyMentor%20Studio%20V2/Parse.NetFx45.DLL

System.Net.Primitives
   גירסת הרכבה: 4.0.0.0
   גירסת Win32: 4.0.30319.33440
##    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Net.Primitives/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Net.Primitives.dll

System.IO
   גירסת הרכבה: 4.0.0.0
   גירסת Win32: 4.0.30319.33440
##    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.IO/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.IO.dll

System.Configuration
   גירסת הרכבה: 4.0.0.0
   גירסת Win32: 4.0.30319.33440 built by: FX45W81RTMREL
##    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll

System.Xml
   גירסת הרכבה: 4.0.0.0
   גירסת Win32: 4.0.30319.33440 built by: FX45W81RTMREL
##    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll

System.Text.RegularExpressions
   גירסת הרכבה: 4.0.0.0
   גירסת Win32: 4.0.30319.33440
##    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Text.RegularExpressions/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Text.RegularExpressions.dll

System.Globalization
   גירסת הרכבה: 4.0.0.0
   גירסת Win32: 4.0.30319.33440
##    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Globalization/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Globalization.dll

AudioSoundEditor
   גירסת הרכבה: 1.0.0.0
   גירסת Win32: 4.1.1.0
##    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/AudioSoundEditor/1.0.0.0__6dd52dbb299cc1b2/AudioSoundEditor.dll

AudioSoundRecorder
   גירסת הרכבה: 1.0.0.0
   גירסת Win32: 6.1.2.0
##    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/AudioSoundRecorder/1.0.0.0__6dd52dbb299cc1b2/AudioSoundRecorder.dll

AudioDjStudio
   גירסת הרכבה: 1.0.0.0
   גירסת Win32: 6.4.2.3
##    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/AudioDjStudio/1.0.0.0__6dd52dbb299cc1b2/AudioDjStudio.dll

System.Windows.Forms.resources
   גירסת הרכבה: 4.0.0.0
   גירסת Win32: 4.0.30319.33440 built by: FX45W81RTMREL
##    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_he_b77a5c561934e089/System.Windows.Forms.resources.dll

mscorlib.resources
   גירסת הרכבה: 4.0.0.0
   גירסת Win32: 4.0.30319.33440 built by: FX45W81RTMREL
##    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_he_b77a5c561934e089/mscorlib.resources.dll

Accessibility
   גירסת הרכבה: 4.0.0.0
   גירסת Win32: 4.0.30319.33440 built by: FX45W81RTMREL
##    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll

System.Linq
   גירסת הרכבה: 4.0.0.0
   גירסת Win32: 4.0.30319.33440
##    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Linq/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Linq.dll

System.Runtime.Extensions
   גירסת הרכבה: 4.0.0.0
   גירסת Win32: 4.0.30319.33440
##    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Extensions/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Runtime.Extensions.dll

System.Linq.Expressions
   גירסת הרכבה: 4.0.0.0
   גירסת Win32: 4.0.30319.33440
##    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Linq.Expressions/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Linq.Expressions.dll

Anonymously Hosted DynamicMethods Assembly
   גירסת הרכבה: 0.0.0.0
   גירסת Win32: 4.0.30319.34003 built by: FX45W81RTMGDR
##    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/mscorlib/v4.0_4.0.0.0__b77a5c561934e089/mscorlib.dll

System.Text.Encoding
   גירסת הרכבה: 4.0.0.0
   גירסת Win32: 4.0.30319.33440
##    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Text.Encoding/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Text.Encoding.dll

System.Net.Http
   גירסת הרכבה: 4.0.0.0
   גירסת Win32: 4.0.30319.33440 built by: FX45W81RTMREL
##    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Net.Http/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Net.Http.dll

Ionic.Zip
   גירסת הרכבה: 1.9.1.8
   גירסת Win32: 1.9.1.8
##    CodeBase: file:///C:/Program%20Files%20(x86)/MyMentor%20Studio%20V2/Ionic.Zip.DLL

Newtonsoft.Json
   גירסת הרכבה: 4.5.0.0
   גירסת Win32: 5.0.8.16617
##    CodeBase: file:///C:/Program%20Files%20(x86)/MyMentor%20Studio%20V2/Newtonsoft.Json.DLL

Microsoft.GeneratedCode
   גירסת הרכבה: 1.0.0.0
   גירסת Win32: 4.0.30319.33440 built by: FX45W81RTMREL
##    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll

*************\* איתור באגים בשיטת JIT **************
כדי להפוך את  just-in-time (JIT) debugging לזמין, the .config יש להגדיר
בקובץ התצורה של היישום או המחשב (machine.config) את הערך
 system.windows.forms במקטע jitDebugging.
כמו כן, יש לבצע ליישום קומפילציה עם  jitdebugging
זמין.

For לדוגמה:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

כאשר JIT debugging זמין, כל חריג שאינו מטופל
יישלח אל JIT debugger הרשום במחשב
במקום שיטופל על-ידי תיבת דו-שיח זו.

**Comment by ariel1974** [comment]
על איזה לחצן לחצת ? מה בדיוק עשית ?

**Comment by natan1957** [comment]
לחצתי על הכפתור האדום, כפי שניתן לראות הוא לחוץ, ואז לחצתי על כפתור המינוס כדי למחוק עוגנים אדומים.
שלחתי לך את הקובץ .

**Comment by natan1957** [comment]
זה עדיין קורה
![image](https://f.cloud.github.com/assets/6491631/2076888/dfc3a45a-8da9-11e3-82fd-e6783ce19799.png)
