### ISSUE TITLE
הפעלת התוכנה

### ISSUE THREAD

**Issue by natan1957** [ariel1974/mymentor#38]
הפעלה אפשרית רק ע"י הפעלה כמנהל

**Comment by ariel1974** [comment]
מה זאת אומרת ?

**Comment by natan1957** [comment]
רק עם האופציה הזאת אני מצליח להפעיל את התוכנה
זה לא מתאים למשתמשים...
![image](https://f.cloud.github.com/assets/6491631/2076097/2c2dac46-8d9b-11e3-85de-b427805ec18a.png)

**Comment by ariel1974** [comment]
מבדיקה שלי במחשב בתול זה תקין

**Comment by natan1957** [comment]
אתקין על מחשב נוסף.

**Comment by natan1957** [comment]
התקנתי על מחשב אחר. מע הפעלה 8.1
עדיין בהורדת קובץ ההתקנה הוא מקשה ומחייב לענות "התקן בכל זאת".
לאחר ההתקנה, גם כאן לא ניתן להפעיל את התוכנה אלא ע"י מנהל. כמו בתמונה שצירפתי.
לאחר ההפעלה אני מקבל הודעה:
Cannot load file sound_sample.mp3
בלחיצה על התחל בבדיקת הקלטה אני מקבל הודעת שגיאה:
![image](https://f.cloud.github.com/assets/6491631/2107619/b3adfad8-8fce-11e3-807f-56b854c97eaf.png)

**Comment by natan1957** [comment]
,העברתי קובץ של הפטרה למחשב החדש ואני מנסה לפתוח אותו.
הוא נותן לי הודעה ניסיון טעינה של קובץ המוזיקה נכשל בגלל הסיבה 
ERR_GENERIC
אם אני מנסה לייבא את הקובץ בנפרד הוא נותן הודעה
Cannot load file: c:......
