### ISSUE TITLE
פתיחת קובץ לאחר הפעלה

### ISSUE THREAD

**Issue by natan1957** [ariel1974/mymentor#39]
מיד לאחר ההפעלה של הסטודיו, כשאני מבקש לפתוח קובץ שנשמר בעבר בדיסק, אני מקבל הודעה לא רלוונטית הבאה :
![image](https://f.cloud.github.com/assets/6491631/2068968/5e69bf4e-8d12-11e3-9ab2-2d2e9e83d7fd.png)

**Comment by natan1957** [comment]
שלחת גרסה ?

**Comment by ariel1974** [comment]
זה טופל
