### ISSUE TITLE
להוסיף כפתור "הדבק". כדי לאפשר להדביק תוכן שהועתק ממקום אחר.

### ISSUE THREAD

**Issue by ariel1974** [ariel1974/mymentor#4]

**Comment by ariel1974** [comment]
הוספתי כבר....

**Comment by natan1957** [comment]
לא יודע לאן נעלמה ההודעה שלי... אני ביקשתי לתקן את הכיתוב שמופיע כאשר עוברים עם הסמן על הכפתור.
בנוסף יש להוסיף כפתור גזירה.
