### ISSUE TITLE
חלון הסאונד נעלם

### ISSUE THREAD

**Issue by natan1957** [ariel1974/mymentor#44]
זה לא קורה לעיתים קרובות, אבל קורה...

![image](https://f.cloud.github.com/assets/6491631/2104601/6e751aa6-8f7d-11e3-807e-35c050b270c8.png)

**Comment by natan1957** [comment]
היום זה קרה שוב
![image](https://f.cloud.github.com/assets/6491631/2148369/0a587b74-93e4-11e3-8f5e-10000d4ff450.png)

**Comment by natan1957** [comment]
הייתה תקלה ותוקנה? או שלא הצלחת לשחזר את התופעה?

**Comment by ariel1974** [comment]
שחזרתי ותוקן.
