### ISSUE TITLE
קביעת מעבר ראשון

### ISSUE THREAD

**Issue by natan1957** [ariel1974/mymentor#45]
עם ההקשה הראשונה על הפטיש(אין עדיין מעברים בקובץ) יש להציב גם מעבר ראשון בזמן 0.01 וגם את המעבר השני על פי זמן ההקשה.

**Comment by ariel1974** [comment]
נתן זה עדיין לא ברור לי , מה יהיה עם קובץ שיש קטע שקט בהתחלה ? התזמון של הקטע הראשון יכלול את הקטע השקט

**Comment by natan1957** [comment]
מה שברור זה שבין נקודת האפס לבין תחילת הקריאה צריך לבא מעבר.
המעבר תפקידו לסלק את הקטע השקט שלפני הקריאה.
עכשיו השאלה מה קורה כשמתחילים את התזמון...
אם הקטע השקט ארוך, כדי לקבוע את המעבר צריך להתמקד בסמן ולקראת הגעתו לתחילת
הסאונד, להקיש על הפטיש. ברוב המקרים יהיה צריך לחזור לנקודה עם בחירה וזום
ולתקן את מיקום המעבר.
אבל אם הקטע השקט קצר מאוד, אף פעם לא מספיקים להקיש על הפטיש בזמן ולמעשה
מקישים בתוך המילים הראשונות. זה מבלבל ומלחיץ כאילו התזמון השתבש על ההתחלה.
ואז צריך לעשות זום ולתקן...
לשיטתי, מיד עם התחלת התזמון ייקבע מעבר ראשון קרוב לאפס. אם הקטע השקט קצר,
אין מה לתקן. אם הקטע השקט ארוך, אפשר בסוף התזמון לחזור לנקודת ההתחלה ולתקן
את המיקום של המעבר הראשון ולקרב אותו לתחילת הסאונד(לא חובה).

2014-02-14 8:42 GMT+02:00 Ariel Illouz notifications@github.com:

**Comment by ariel1974** [comment]
לא פשוט עדיף כברירת מחדל לשתול 3 שניות של שקט לפני הקלטה או בעת יבוא הקלטה ?

**Comment by natan1957** [comment]
למה לא פשוט? מבחינה טכנית? אפשר לשתול מעבר ראשון בזמן אפס?

נשלח מה-iPhone שלי

ב-Feb 14, 2014, בשעה 17:35, Ariel Illouz notifications@github.com כתב/ה:

**Comment by ariel1974** [comment]
זה שובר את הרצף
כשיסומן איזה קטע בטקסט יסומן?

**Comment by natan1957** [comment]
לא הבנתי. האם לא ניתן מיד אחרי התחלת התזמון ליזום לחיצה על הפטיש? כאילו המשתמש לחץ?...

נשלח מה-iPhone שלי

ב-Feb 14, 2014, בשעה 18:52, Ariel Illouz notifications@github.com כתב/ה:

> זה שובר את הרצף 
> כשיסומן איזה קטע בטקסט יסומן?

**Comment by ariel1974** [comment]
אוקיי
