### ISSUE TITLE
זום לסמן

### ISSUE THREAD

**Issue by natan1957** [ariel1974/mymentor#51]
בזמן לחיצה על זום, אם בסמן מוצב בחלון הסאונד, הזום צריך לשאוף להביא אותו לאמצע המסך ככל הניתן.
הסמן לא יגיע לאמצע המסך במקרה שהוא קרוב לתחילת הסאונד או לסוף הסאונד.

**Comment by ariel1974** [comment]
נשלחה בקשה ל-Support
לא פשוט לעשות את זה
