### ISSUE TITLE
מחיקת תזמונים

### ISSUE THREAD

**Issue by natan1957** [ariel1974/mymentor#52]
יש לאפשר למחוק את כל התזמונים מהסמן ועד הסוף

**Comment by natan1957** [comment]
מחיקת התזמונים עובדת.
אבל לאחר מכן, כשמנסים להמשיך את התזמון, ע"י ניגון מקטע קודם, קטע הטקסט שאחרי התזמון האחרון שנשאר לא נדלק.
לכן קיימת בעיה לתזמן את ההמשך

**Comment by ariel1974** [comment]
איך אני אסמן אותו כשאני לא יודע מה הסוף שלו?

**Comment by natan1957** [comment]
הסוף שלקטע הטקסט ידוע - העוגן הבא...

2014-02-16 16:17 GMT+02:00 Ariel Illouz notifications@github.com:

> איך אני אסמן אותו כשאני לא יודע מה הסוף שלו?

**Comment by ariel1974** [comment]
אין עוגן הבא, אני לא מבין

2014-02-16 16:24 GMT+02:00 natan1957 notifications@github.com:

> הסוף שלקטע הטקסט ידוע - העוגן הבא...
> 
> 2014-02-16 16:17 GMT+02:00 Ariel Illouz notifications@github.com:
> 
> > איך אני אסמן אותו כשאני לא יודע מה הסוף שלו?
