### ISSUE TITLE
בחירת סאונד ע"י הקלקה על עוגן

### ISSUE THREAD

**Issue by natan1957** [ariel1974/mymentor#53]
כשמקישים על עוגן מתוזמן יש לבצע בחירת טווח סאונד לפני ואחרי המעבר המתאים במרחק שלנקבע  בהיסט עליון/תחתון
יש לצבוע את המעבר הנבחר בצבע שונה.

**Comment by natan1957** [comment]
הבחירה עובדת.
זה מחייב להקיש על הצג הימני של העוגן.
אם מקישים על הצד השמאלי שלו, מתבצעת בחירת קטע הטקסט שאחריו
האם התחלה וסוף הם עוגנים? האם ניתן שגם הקלקה עליהם גם תבצע בחירה, זה נחוץ לשם כיוון המעבר הראשון והאחרון

**Comment by ariel1974** [comment]
זה באג?

**Comment by natan1957** [comment]
לחיצה על העוגן צריכה לבצע פעולה אחת והיא בחירה סביב המעבר. תוך כדי הדלקת
העוגן.
בל אם לוחצים בחלק השמאלי בתוך העוגן, משמאל מספר, זה מבצע בחירת טקסט.
זה לא תקין.

2014-02-16 16:18 GMT+02:00 Ariel Illouz notifications@github.com:

> זה באג?
