### ISSUE TITLE
 לחצני הקפצת סמן להתחלה  ולסוף

### ISSUE THREAD

**Issue by natan1957** [ariel1974/mymentor#56]
אם קיימת בחירת סאונד, הסמן יקפוץ להתחלת הבחירה ולסוף הבחירה בהתאם.

**Comment by ariel1974** [comment]
הסמן נהיה סמן כשאין בחירה. במצב בחירה אם אסמן את תחילת הבחירה, הבחירה תעלם. כך זה מתנהג כברירת מחדל - תשים לב שהסמן הצהוב לא יופיע לך לעולם כשאתה במצב בחירת קטע

**Comment by natan1957** [comment]
אבל כאשר מבצעים ניגון בחירה, רואים סמן שמתקדם בתוך הבחירה. המטרה היא, שבזמן השמעת בחירה, ניתן יהיה לעצור, להמשיך, לדלג להתחלת בחירה כדי לנגן שוב וכו׳. אולי במקום הצבה פיזית של סמן, אפשר לדרוך את זמן נוכחי לתחילת בחירה. כך שאם לוחצים נגן או נגן בחירה, זה ינגן מתחילת הבחירה. 

נשלח מה-iPhone שלי

ב-Feb 15, 2014, בשעה 8:50, Ariel Illouz notifications@github.com כתב/ה:

**Comment by ariel1974** [comment]
כך הנגן מתנהג לבד, אין לי שליטה על זה - אי אפשר להציב סמן + בחירה

2014-02-15 9:53 GMT+02:00 natan1957 notifications@github.com:

**Comment by natan1957** [comment]
זה פשוט.
לאחר ביצוע בחירה הסמן מתייצב לבד בתחילתה.
אז להציב את הסמן בתחילת הבחירה ניתן ע"י ביצוע בחירה מחודשת לטווח הבחירה הנוכחי.
ייתכן ולהבאת הסמן לסוף הבחירה אין פתרון וזה גם לא נחוץ.
מה שנחוץ זה הבאת הסמן לתחילת הבחירה כדי לנגן את הבחירה מתחילתה.

**Comment by ariel1974** [comment]
אבל שוב....אם אני שם את הסמן...הבחירה תעלם

**Comment by natan1957** [comment]
לפי דעתי אתה לא צריך לשים את הסמן, אחרי הבחירה הוא כבר יהיה שם.
כשמבצעים בחירה ולוחצים על התחל/המשך של תזמון קטעים, זה מתחיל לנגן מתחילת
הבחירה ...
הכפתור נגן בחירה צריך לעשות זאת.

2014-02-16 16:16 GMT+02:00 Ariel Illouz notifications@github.com:

> אבל שוב....אם אני שם את הסמן...הבחירה תעלם

**Comment by ariel1974** [comment]
לא הבנתי, דבר איתי

2014-02-16 16:23 GMT+02:00 natan1957 notifications@github.com:

> לפי דעתי אתה לא צריך לשים את הסמן, אחרי הבחירה הוא כבר יהיה שם.
> כשמבצעים בחירה ולוחצים על התחל/המשך של תזמון קטעים, זה מתחיל לנגן מתחילת
> הבחירה ...
> הכפתור נגן בחירה צריך לעשות זאת.
> 
> 2014-02-16 16:16 GMT+02:00 Ariel Illouz notifications@github.com:
> 
> > אבל שוב....אם אני שם את הסמן...הבחירה תעלם
