### ISSUE TITLE
עוגן בסוף הטקסט

### ISSUE THREAD

**Issue by natan1957** [ariel1974/mymentor#57]
יש למנוע מצב של עוגן בסוף הטקסט.
לא לשתול באופן אוטומטי ולהתריע על שגיאה אם שותלים באופן ידני

**Comment by ariel1974** [comment]
המערכת מסירה את האחרון באופן אוטומטי

**Comment by natan1957** [comment]
מתי היא מסירה את העוגן האחרון? 
בקביעת עוגנים אוטומטית זה עדיין קובע עוגן בסוף הטקסט
![image](https://f.cloud.github.com/assets/6491631/2178587/545853b6-966e-11e3-9d0c-29a3c9c12b9a.png)

**Comment by ariel1974** [comment]
תנסה לעבור כרטסת

**Comment by ariel1974** [comment]
שלח לי את הטקסט

**Comment by ariel1974** [comment]
היה באג עם אנטרים בסוף הטקסט, תוקן

גרסה 9.0.1.1

https://drive.google.com/file/d/0B8nKPU4xJkD3b0RwX3d5dmZPWlk/edit?usp=sharing

2014-02-15 20:24 GMT+02:00 natan1957 notifications@github.com:

**Comment by natan1957** [comment]
עדיין לא תקין
כשיש אנטר בסוף הטקסט, המערכת מציבה עוגן.
למשתמש אין דרך לדעת שיש שם אנטר אחד או כמה.
יש למחוק אותם לפני קביעת עוגנים

**Comment by ariel1974** [comment]
שלחתי תיקון - התקנת את האחרון ?

2014-02-16 13:59 GMT+02:00 natan1957 notifications@github.com:

**Comment by natan1957** [comment]
9.0.1.0

2014-02-16 14:20 GMT+02:00 Ariel Illouz notifications@github.com:

**Comment by ariel1974** [comment]
יש יותר חדש
