### ISSUE TITLE
כפתורי עוגנים

### ISSUE THREAD

**Issue by natan1957** [ariel1974/mymentor#58]
הכפתורים צריכים להתנהג כמו
Radio Buttons.
אין מצב ששניים או יותר לחוצים.
לחיצה על אחד משחררת את האחר.

**Comment by ariel1974** [comment]
איך הגעת למצב ששניים לחוצים? אני לא מצליח לשחזר את זה

**Comment by natan1957** [comment]
כאשר הסמן לא מוצב באזור הטקסט
