### ISSUE TITLE
בקביעת עוגנים אוטומטית אין למחוק עוגנים ירוקים

### ISSUE THREAD

**Issue by natan1957** [ariel1974/mymentor#59]
כמו כן, אם מבצעים קביעת עוגנים אוטומטית כאשר סוג עוגן מסוים לא נבחר
הפעולה לא צריכה למחוק עוגנים קיימים מאותו הצבע.
אלא אם עוגן אחר שנקבע במהלך הזה דורס עוגן קיים.

**Comment by ariel1974** [comment]
לא טיפלתי בזה כבר מזמן ?

**Comment by natan1957** [comment]
כרגע זה לא עובד.
שים לב שהחלוקה האוטומטית לא צריכה למחוק עוגנים קיימים אלא רק להוסיף עוגנים על פי החוקים.
ביטול עוגן קיים בחלוקה אוטומטית יקרה רק במקרה של דריסה שלו .

**Comment by natan1957** [comment]
גם אם מפעילים את החלוקה מספר פעמים, זה לא צריך להוסיף עוגנים אלא רק עודן אחד.
אם קיים עוגן נמוך יותר הוא צריך להידרס ע"י עוגן בעל ערך גבוהה יותר ולא להתווסף לצידו

![image](https://f.cloud.github.com/assets/6491631/2492197/97c14c64-b218-11e3-9195-9bed3d58a1c4.png)

**Comment by ariel1974** [comment]
טופל
