### ISSUE TITLE
דריסת פונט בשמירת מקורות

### ISSUE THREAD

**Issue by natan1957** [ariel1974/mymentor#60]
אני מעלה מקור עם פונט מסוים.
כשאני מאחזר אותו , הפונט המקורי נעלם והטקסט מופיע בפונט אריאל גודל 16.
אולי בגלל שזה השם שלך ?...

**Comment by ariel1974** [comment]
טופל, אבל עליך להעלות את המקורות מחדש אחרי שאעלה גרסה כי שיניתי סוג עמודה

**Comment by natan1957** [comment]
להעלות מקורות מחדש?!  קטן עלי
אני מקווה שהתיקון תופס גם לגביי שיעורים רגילים

**Comment by ariel1974** [comment]
את אותם מקורות פשוט שמור שוב
