### ISSUE TITLE
הסרת תזמונים ממעבר נבחר

### ISSUE THREAD

**Issue by natan1957** [ariel1974/mymentor#61]
זה מתאפשר רק כאשר המעבר נבחר על ידי הקלקה על עוגן.
אם אני בוחר מעבר בהקלקה עליו, מחיק עוגנים ממנו עד הסוף לא מאופשרת.

![image](https://f.cloud.github.com/assets/6491631/2457948/159c189a-af43-11e3-9e82-92374a5595bc.png)

**Comment by natan1957** [comment]
לא טופל

**Comment by ariel1974** [comment]
טופל
