### ISSUE TITLE
נושאים שונים במסך בדיקה

### ISSUE THREAD

**Issue by natan1957** [ariel1974/mymentor#63]
יש להצמיד שמאלה את טקסט התקני הקלט כדי שהמידע הרלוונטי לא ייחתך

קופסת הסימון של אל תציג מסך זה מסומנת תמיד. גם אם מבטלים את הסימון וסוגרים ופותחים את המסך, זה מופיע שוב מסומן. ברירת המחדל בהתקנת המערכת צריכה להיות כן להציג.

יש לאחד את דלג והכל בסדר לכפתור אחד - סיים בדיקה

להחליף טקסט התחל הקלטה ל - הקלט והקשב

לשנות את שורת הכותרת ל - 
לפני ביצוע הקלטה או יבוא קובץ סאונד, מומלץ לבדוק את התקני השמע במחשב.
הקלט 5 שניות והקשב להקלטה או הקשב לקובץ דוגמה.

בהקלטה לשנות את הטקסט ל - 
מומלץ להגיע למצב בו עצמת ההקלטה מגיעה לאזור החץ

בפקדי הווליום יש להחליף עוצמה בעצמה.

בהמשך אשלח לך קובץ דוגמה יותר קצר.

האם ההקלטה נשמרת בסטריאו? אם כן יש להחליף למונו כדי שיהיה יותר חסכוני. בהמשך אבדוק את מאפייני הקובץ המוקלט/נשמר

![image](https://f.cloud.github.com/assets/6491631/2491223/fd631734-b1df-11e3-8e4a-03a70a701103.png)

**Comment by natan1957** [comment]
יש לשנות נגן קובץ דוגמא ל נגן קובץ דוגמה

**Comment by ariel1974** [comment]
טופל
