### ISSUE TITLE
פקד עצמת הקלטה

### ISSUE THREAD

**Issue by natan1957** [ariel1974/mymentor#64]
ההתנהגות לא לינארית.
ככל שמורידים את פקד עצמת ההקלטה זה לא משפיע על העצמה, עד שמגיעים לתחתית  ואז העצמה נופלת לאפס.

**Comment by ariel1974** [comment]
לא נכון, זה בסדר - בדקתי הקלטה ארוכה והורדתי כל פעם קצת. זה מתנהג בסדר גמור.

**Comment by natan1957** [comment]
אצלי זה לא תקין. מציע שבהזדמנות תתחבר למחשב שלי ותראה
