### ISSUE TITLE
.מעברים נעלמים בפתיחת קובץ שתוזמן

### ISSUE THREAD

**Issue by natan1957** [ariel1974/mymentor#65]
בפתיחת קובץ שתוזמן, אם עוברים ישר למסך התזמון, המעברים לא מוצגים. רק אחרי שעוברים להקלטה ואז לתזמון, הם מופיעים.

בנוסף, בפתיחת מסך התזמון, העוגן התחלה מסומן וקיימת בחירה סביב המעבר הראשון. אם לוחצים נגן מתנגנת הבחירה. זה לא טוב. בפתיחה ראשונה של מסך התזמון הסמן צריך לעמוד בתחילת הקובץ כשאף עוגן או מעבר לא נבחר.

**Comment by ariel1974** [comment]
למה זה לא משתחזר לי ?

**Comment by natan1957** [comment]
זה קורה לי שוב ושוב כאשר אני טוען קובץ ואחר כך טוען קובץ אחר.
אז, אם אני עובר יש לתזמון, המעברים לא מופיעים.

**Comment by ariel1974** [comment]
אבדוק

**Comment by ariel1974** [comment]
זה קרה כהולכים ישירות לפרסום ואז לתזמון
