### ISSUE TITLE
ממשק אנגלי

### ISSUE THREAD

**Issue by natan1957** [ariel1974/mymentor#67]
בנושא זה כאילו העבודה נעצרה באמצע...
המסכים לא הופכים כיוון, למרות שבעבר כבר ראיתי שיש היפוך.

שמות של שדות וטקסטים קבועים לא מתחלפים לאנגלית

בחיפוש מקור, שמות המקורות צריכים להיות מוצגים בהתאם לשפת הממשק. יש להוסיף עמודת הערה ולהציג  באופן הבא:
בעברית: ראשי, פרשה, קריאה, הערה.   בעמודה נוספת: הערה אנגלית
in English: rashi, parasha, kria, heara anglit.   בעמודה נוספת: heara

אחרי התיקונים האלה אוכל להמשיך לבדוק את העניין.

**Comment by natan1957** [comment]
שים לב להנחיה על שמות מקורות

**Comment by ariel1974** [comment]
פרט הסבר נמק

**Comment by natan1957** [comment]
אז ככה...
לכל שיעור יש שני שמות: שם בעברית (זה שכבר קיים) ושם באנגלית (זה שעדיין לא
טופל...).
כפי שהשם בעברית מורכב משרשור של שמות הקטגוריות בעברית + תוספת לשם שיעור, כך
שם השיעור באנגלית מורכב משרשור של שמות הקטגוריות באנגלית + תוספת לשם שיעור
באנגלית.
זה נכון לשיעורים ולמקורות.
כאשר בוחרים את הקטגוריות ומייצרים שם עברי, במקבל יש לייצר שם אנגלי.
את השם באנגלית יש לשמור בטבלת הקליפים בשדה בשם nameEnglish.

במסך חיפוש מקורות יש להוסיף עמודה עבור תוספת לשם שיעור.
כאשר מאחזרים מקורות בממשק עברי, יש להציג את השם בעברית(המשורשר כולל תוספת
לשם שיעור) ובעמודה הנוספת את תוספת לשם שיעור באנגלית
כאשר מאחזרים מקורות בממשק אנגלי, יש להציג את השם באנגלית (המשורשר כולל
תוספת לשם שיעור באנגלית) ובעמודה הנוספת את תוספת לשם שיעור.

**Comment by natan1957** [comment]
באותה ההזדמנות, מכיון ששמתי לב שאתה מבצע את השרשורים בעזרת טבלת העולמות, יש
לשנות גם את טבלת העולמות לשיטה אליה העברת את כל הטבלאות.
ז"א שורה אחת לכל עולם כאשר לכל שפה יש את העמודות שלה.
בטבלת המשתמשים יש להוסיף שדה עולם תוכן. יש לפנות לעולם התוכן הרלוונטי (זה
שמעודכן ברשומת המשתמש) בכל פעם שמפעילים את הסטודיו, לטעון את הטבלאות של
העולם הרלוונטי. (כרגע אני מניח שבכל מקרה נטען עולם התורה.)
לפי דעתי אתה היחיד שניגש בשלב זה לטבלה, אבל תום צריך להיות מעודכן.
שים לב שבטבלת העולמות יש סטטוס, הוא נועד לאפשר שבשלב הקמת עולם חדש לא תהיה
אליו נגישות של המשתמשים אלא למנהלים ולקבוצת משתמשים מצומצמת. קבוצת הבודקים.
משתמש יראה את עולם התוכן (בפורטל) ויוכל לעבור אליו, רק אם העולם בסטטוס PROD
או שהעולם בסטטוס PREPROD ולמשתמש יש את העולם בעמודת TestTeamMember (צריך
לפתוח שדה זה.).
למנהל יש גישה לכל העולמות בכל הסטטוסים.
מבחינת הסטודיו, הוא ניגש לעולם שמעודכן ברשומת המשתמש.

2014-04-06 22:31 GMT+03:00 Natan Helfman nhelfman@gmail.com:

> אז ככה...
> לכל שיעור יש שני שמות: שם בעברית (זה שכבר קיים) ושם באנגלית (זה שעדיין לא
> טופל...).
> כפי שהשם בעברית מורכב משרשור של שמות הקטגוריות בעברית + תוספת לשם שיעור,
> כך שם השיעור באנגלית מורכב משרשור של שמות הקטגוריות באנגלית + תוספת לשם
> שיעור באנגלית.
> זה נכון לשיעורים ולמקורות.
> כאשר בוחרים את הקטגוריות ומייצרים שם עברי, במקבל יש לייצר שם אנגלי.
> את השם באנגלית יש לשמור בטבלת הקליפים בשדה בשם nameEnglish.
> 
> במסך חיפוש מקורות יש להוסיף עמודה עבור תוספת לשם שיעור.
> כאשר מאחזרים מקורות בממשק עברי, יש להציג את השם בעברית(המשורשר כולל תוספת
> לשם שיעור) ובעמודה הנוספת את תוספת לשם שיעור באנגלית
> כאשר מאחזרים מקורות בממשק אנגלי, יש להציג את השם באנגלית (המשורשר כולל
> תוספת לשם שיעור באנגלית) ובעמודה הנוספת את תוספת לשם שיעור.
>

**Comment by ariel1974** [comment]
מחקתי בטעות את עמודת סטאטוס בטבלת עולמות
תוסיפו אותה, שיניתי לפי דרישתך את הטבלאות והתאמתי את הסטודיו לעבוד כמו שחפרת למעלה

**Comment by natan1957** [comment]
בדקת שזה עובד? כי זה לא...

**Comment by ariel1974** [comment]
מתעופף? פרסמת ו הוא לא שתל שם אנגלי?

**Comment by natan1957** [comment]
לא מתעופף אבל גם לא עובד.
כמובן שפרסמתי. לא בדקתי בטבלה, אבל פרסמתי בממשק עברי ואחזרתי בממשק אנגלי והשם האנגלי לא הוצג.
שים לב שלשם השיעור יש לשרשר את השדה תוספת לשם שיעור ולא את שדה תיאור. ובהתאמה גם באנגלית.
ללא קשר לממשק בו נמצאים, שם השיעור צריך להתחולל גם בעברית וגם באנגלית. להיות מוצג על פי הממשק הנוכחי אבל להישמר בטבלה בשתי השפות.
לעמודה הנוספת שמציגה את תוספת לשם שיעור של השפה השנייה לא התייחסת כלל.

**Comment by ariel1974** [comment]
אתה יכול לשנות את הpattern בעצמך זה כל הרעיון
פשוט שתול שם [remarks]

**Comment by ariel1974** [comment]
![image](https://cloud.githubusercontent.com/assets/3278964/2664059/8c8ed02e-c06d-11e3-8f21-a0838a62e428.png)

**Comment by ariel1974** [comment]
למה אתה מתכוון "אחזרתי" בממשק האנגלי ?

**Comment by ariel1974** [comment]
יצרתי מקור בעברית
אחזרתי אותו באנגלית

![image](https://cloud.githubusercontent.com/assets/3278964/2664076/2e99743c-c06e-11e3-8ada-8a22fb66e1da.png)

**Comment by natan1957** [comment]
זה כתוצאה מהתיקון האחרון? או אצלך זה עובד...?
יש להוסיף עמודה עם שדה תוספת לשם שיעור. בממשק אנגלי יש להכניס שם את התוכן
העברי (תוספת לשם שיעור) ובממשק עברי יש להכניס שם את התוכן האנגלי(תוספת לשם
שיעור באנגלית).
אתה רואה שבאחזור האנגלי, הקטגוריות ראשי ופרשה נשארים ריקים... למה אתה לא
מסדר את זה...

**Comment by ariel1974** [comment]
אני לא מבין, עמודה חדשה בטבלה? במסך?

**Comment by natan1957** [comment]
במסך תוצאות חיפוש מקורות. 

נשלח מה-iPhone שלי

ב-Apr 10, 2014, בשעה 9:28, Ariel Illouz notifications@github.com כתב/ה:

> אני לא מבין, עמודה חדשה בטבלה? במסך?

**Comment by natan1957** [comment]
שם העמודה באנגלית צריך להיות
name extension
לאור תוספת העמודה השדות נחתכים. יש להרחיב את החלון של חיפוש מקורות כדי להקטין את התופעה.
