### ISSUE TITLE
שינוי גודל פונט

### ISSUE THREAD

**Issue by natan1957** [ariel1974/mymentor#69]
הפקדים +A -A 
לא מתפקדים כאשר יש טקסט מעורב ומורכב.
אתה יכול לבדוק לדוגמה את המקור 
שמות, שמות, קריאה1, הערה עברית בדיקת פונטים

**Comment by ariel1974** [comment]
הרכיב הוא מובנה, ובמקרים מסויימים - בדיוק כמו בוורד - לא תוכל לבצע את
הפעלויות הללו
אין לי מה לתקן/לשפר כאן.

2014-03-23 13:35 GMT+02:00 natan1957 notifications@github.com:

**Comment by natan1957** [comment]
אני מעתיק את הטקסט לוורד ושם זה עובד...

2014-03-23 13:40 GMT+02:00 Ariel Illouz notifications@github.com:

**Comment by ariel1974** [comment]
טוב בוא לא נגזים אני עדיין לא וורד, זה רכיב סגור שמדמה rich text....אין לי
אפשרות להתערב בתהליך הזה של הגדלת טקסט, יש לי פשוט פקודה - הגדל פונט.

2014-03-23 13:46 GMT+02:00 natan1957 notifications@github.com:

**Comment by natan1957** [comment]
אבל כאשר אני מצמצם את הטקסט באיזה שהו שלב זה מתחיל לעבוד. ז"א שמשהו בטקסט
מפריע לו לתפקד. צריך למצוא מה ולבעוט לו בתחת (השמן שלו...)

2014-03-23 14:01 GMT+02:00 Ariel Illouz notifications@github.com:

**Comment by ariel1974** [comment]
סבבה, נסה למצוא איזה תו מפריע לו - אמשוך אותו מהטקסט.

2014-03-23 14:17 GMT+02:00 natan1957 notifications@github.com:

**Comment by natan1957** [comment]
בטקסט פשוט שמתי לב שיש שורות שלא מתחילות מההתחלה.
כל זמן ששורות אלה נמצאות הפונקציה לא עובדת. ברגע שאני מסיר אותן היא עובדת.

**Comment by natan1957** [comment]
![image](https://f.cloud.github.com/assets/6491631/2493526/1287f97c-b299-11e3-940d-49a888d4bb61.png)

**Comment by ariel1974** [comment]
בדקתי את הנושא לעומק. כשיש לך עירוב של פונטים בקטע הנבחר - לא ניתן לבצע הגדלה

**Comment by natan1957** [comment]
פונט מעורב לא מטופל, אפילו אם אותו הפונט אבל תערובת מודגש ולא מודגש. י שלהשלים את הטיפול בזה.

שינוי פונט לא תקין הואיל והוא מחובר לשינוי גודל. אם בוחרים את כל הפרק וקובעים לו פונט מסוים, כל הפרק מקבל את אותו הגודל.
יש להפריד בין פונט לגודל רצוי לנהל רשימת פונטים כדי לוודא שליטה ושפונטים לא נתמכים לא יהיו בה.

**Comment by ariel1974** [comment]
זה רכיב סגור, ניסיתי להתחכם וזה לא כל כך הולך. מה שאני יכול לעשות זה להגדיל
את כל הטקסט בהתאמה - לא לאותו גודל, אבל את כל הטקסט בלבד

**Comment by natan1957** [comment]
בסדר.
שינוי גודל עם פלוס ומינוס, מטפל בכל הטקסט.
שינוי גודל דרך הגדרת גודל פונט (שאמרתי שיש להפריד מסוג פונט כי זה מיישר את
הגודל של כל הטקסט) משנה את הטקסט הנבחר.

2014-05-24 7:53 GMT+03:00 Ariel Illouz notifications@github.com:

**Comment by natan1957** [comment]
הועבר לסעיף 124
