### ISSUE TITLE
מהירות השמעה איטית

### ISSUE THREAD

**Issue by natan1957** [ariel1974/mymentor#70]
יש להגביל את המהירות האיטית הגבלה נוספת.
כרגע שמתי לב שהמהירות הכי איטית המותרת היא כאשר הפקד במצב שבתמונה.
אני לא יכול לתת ערך מספרי אלא רק תמונה....
אחרי שתשנה ואקשיב אוכל לדעת אם זה מספיק או שצריך עוד.

![image](https://f.cloud.github.com/assets/6491631/2493214/8f173912-b285-11e3-887e-80264e90f57f.png)

**Comment by ariel1974** [comment]
ההגבלה היא +100 עד -70
ציין טווח חדש

2014-03-23 14:22 GMT+02:00 natan1957 notifications@github.com:

**Comment by natan1957** [comment]
לא יודע. אם תציג לי באופן זמני את הערך של הפקד אוכל להגיד.

2014-03-23 14:23 GMT+02:00 Ariel Illouz notifications@github.com:

**Comment by ariel1974** [comment]
הוספתי הצגה באופן זמני

**Comment by natan1957** [comment]
המהירות האיטית ביותר האפשרית תהיה מינוס שלושים וחמש
