### ISSUE TITLE
בחירת עוגן

### ISSUE THREAD

**Issue by natan1957** [ariel1974/mymentor#71]
העוגן נמצא בחפיפה עם הטקסט. כך שאם מקישים על העוגן באזור השמאלי שלו, אז במקום בחירת העוגן נבחר הטקסט.
יש לבטל את החפיפה כדי שזה לא יקרה.
![image](https://f.cloud.github.com/assets/6491631/2493344/579c72d6-b28f-11e3-99cf-147fe7070b55.png)

**Comment by natan1957** [comment]
לא טופל.

**Comment by ariel1974** [comment]
למה לא ? אצלי זה בסדר, והעוגן יושב בדיוק

**Comment by natan1957** [comment]
כאשר הפונט קטן ייתכן שאתה צודק. אבל בפונט גדול יותר זה מתנהג כפי שאמרתי.
לדוגמה בתמונה המצורפת באחת ההודעות הקודמות, אם הלחיצה תהיה על הסוגר השמאלי זה ידליק את הטקסט ולא את העוגן
