### ISSUE TITLE
קיצורים ופקדים

### ISSUE THREAD

**Issue by natan1957** [ariel1974/mymentor#73]
יש להוסיף את הפקדים שמירה, גזירה והדבקה
יש לאפשר את קיצורי הדרך הבאים
ctr a     select all
ctr x     cut selection
ctr c    copy selection
ctr v    paste
del      del selection
ctr s    save file
ctr +   zoom in
ctr -   zoom out

**Comment by natan1957** [comment]
סימנת את הקיצורים בתפריט. יפה. אבל, המתחיל במצווה אומרים לו גמור... תוסיף גם בתפריט זום...

לא הוספת את גזירה והדבקה

כפתור שמירה לא דומה לשום דבר, למה לא לקחת את הכפתור השמירה ממסך טקסט?

**Comment by ariel1974** [comment]
יש בעיה טכנית להציג Ctrl + +
הוא מציג משהו הזוי כמו 
Ctrl + OemPlus

**Comment by ariel1974** [comment]
זה האתר של האייקונים - בחר כאוות נפשך

https://www.iconfinder.com/search/?q=save&maximum=32&price=free

**Comment by natan1957** [comment]
כפתור שמירה, אם לא ניתן להשתמש עם זה שבמסך טקסט אז לקחת את זה:
https://www.iconfinder.com/icons/173091/download/svg/64

טעינת קובץ שמע להחליף לזה:
https://www.iconfinder.com/icons/7495/folder_sound_icon#size=96
לסלק את טעינת קובץ שמע ממסך תזמון

זום, אם לא ניתן 
ctr +, ctr -
אז לרשום 
ctr plus,  ctr minus
