### ISSUE TITLE
המשך הקלטה

### ISSUE THREAD

**Issue by natan1957** [ariel1974/mymentor#74]
הפונקציה עובדת אבל לא מכוונת למעבר חלק.
זה היה גם בגרסה הקודמת ותיקנת את זה שם.

את הכתובית המשך הקלטה לשנות ל נגן עד הסוף והקלט 

הפקד נראה כאילו הוא שתי פונקציות נפרדות האם ניתן לתחום בקווים או משהו...

![image](https://f.cloud.github.com/assets/6491631/2493395/cb1aaaf4-b292-11e3-8e17-a2a6e1675c00.png)

להגדיל את המשולש של פקד הניגון לגודל מקסימלי בתוך הכפתור

**Comment by natan1957** [comment]
עדיין לא תקין אני שולך לך במייל הקלטה של הקלטת המשך

עדיין לא הגדלת את המשולש של הכפתור נגן

**Comment by ariel1974** [comment]
אין לי מקום בלחצן.

**Comment by natan1957** [comment]
אני שולח לך את הקובץ
שים לב שבין הארבע לחמש התווסף קטע שהוא החלק האחרון של הארבע
![image](https://cloud.githubusercontent.com/assets/6491631/2530044/5c2eb472-b522-11e3-922d-4f7cbb188141.png)

**Comment by natan1957** [comment]
המשך השתפר, בשלב זה זה מספיק.
מקווה שלא יתגלו מקרים שזה משתבש

בנוגע למשולש הניגון, התכוונתי לכפתור ניגון ולא לכפתור נגן והקלט.
מתנצל אל אי ההבנה

**Comment by ariel1974** [comment]
אתה לא אמיתי
