### ISSUE TITLE
נושאים שונים

### ISSUE THREAD

**Issue by natan1957** [ariel1974/mymentor#75]
במעבר ראשון למסך, שדה קריאה מאוכלס. צריך להיות ריק.

רק ליד שדה קריאה יש כוכבית חובה. יש להוסיף כוכביות חובה ליד כל שדות החובה: ראשי, פרשה, קריאה, נוסח, תאריכי קריאה, מחיר.

תאריכי קריאה חייבים להיות גדולים מתאריך היום.

שדות נעילה ושלבי לימוד צריכים להיות בברירת מחדל מסומנים ולא נעולים

 שמות השדות הערה והערה באנגלית יש להחליף ל  תוספת לשם שיעור ו תוספת לשם שיעור באנגלית. 

כשאני פותח קובץ מקור מהדיסק, שדה הערות אנגלית לא מוצג

כשאני מביא מקור מהמאגר שדות הערות אנגלית והערות עברית לא מופיעים.

שדות אנגלית יש להצמיד לשמאל

**Comment by ariel1974** [comment]
שדה הערה באנגלית לא נשמר אי פעם - עליך לפרסם מקור שוב - ולבדוק

**Comment by natan1957** [comment]
האם ניתן להזיז את הכוכביות כך שיהיה בגובה אמצע שם השדה ?
יש לסלק כוכביות של שדות שלא במסך במצב מקור
![image](https://cloud.githubusercontent.com/assets/6491631/2530307/d92256bc-b524-11e3-98a3-71e50273ca3d.png)

לחיצה על חדש צריכה לנקות את הקטגוריות שמסך פרסום
פרשה/מועד לא מנוכה

כשאני שומר מקור על הדיסק ופותח אותו, השדות פרשה/מועד ותוספת לשם באנגלית לא מוצגים.

כשאני מביא את המקור מהמאגר, הוא מגיע ללא תוספת לשם באנגלית.

**Comment by ariel1974** [comment]
עליך לשמור שוב את המקור עם האנגלית - ולבדוק שוב, היה באג בעת השמירה

**Comment by natan1957** [comment]
אתה לא אמיתי...

2014-03-27 7:25 GMT+02:00 Ariel Illouz notifications@github.com:

**Comment by ariel1974** [comment]
חחח

**Comment by natan1957** [comment]
בקטנה...
![image](https://cloud.githubusercontent.com/assets/6491631/2534507/4fca781a-b57c-11e3-9649-09b579456674.png)

**Comment by ariel1974** [comment]
ברח...יתוקן הערב

**Comment by ariel1974** [comment]
טופל
