### ISSUE TITLE
בחירה כפולה של מעבר

### ISSUE THREAD

**Issue by natan1957** [ariel1974/mymentor#76]
![image](https://f.cloud.github.com/assets/6491631/2524582/7384cf82-b4e4-11e3-8e53-1323486e8ed5.png)

**Comment by ariel1974** [comment]
יהיה מאוד נחמד אם תאמר לי איך הגעת לזה

**Comment by natan1957** [comment]
הלוואי שהייתי יודע.
אנסה לשחזר אבל לא בטוח שאצליח
