### ISSUE TITLE
אף פקד לא זמן

### ISSUE THREAD

**Issue by natan1957** [ariel1974/mymentor#77]
איך הגעתי לזה?
בצעתי בעזרת מקשי הקיצור 
select all , del
![image](https://cloud.githubusercontent.com/assets/6491631/2529905/9f17d874-b520-11e3-8a91-edf4f2314c76.png)

**Comment by ariel1974** [comment]
תכלס זה מה שהיה אמור לקרות. איך אתה רוצה שאתנהג ? לבטל את המחיקה?

**Comment by natan1957** [comment]
אם אין כלום בזיכרון, כפתור ההקלטה צריך להיות זמין

**Comment by natan1957** [comment]
שחזרת ותיקנת ?

**Comment by ariel1974** [comment]
חיובי. למה, הלחצן לא זמין ?

**Comment by natan1957** [comment]
סתם חשדנות פולנית... מי יודע מה שתלו לך שם במרוקו...

נשלח מה-iPhone שלי

ב-Mar 27, 2014, בשעה 9:26, Ariel Illouz notifications@github.com כתב/ה:

> חיובי. למה, הלחצן לא זמין ? 
>

**Comment by natan1957** [comment]
או בטוניסיה... איפה היית?

נשלח מה-iPhone שלי

ב-Mar 27, 2014, בשעה 11:03, Natan nhelfman@gmail.com כתב/ה:

> סתם חשדנות פולנית... מי יודע מה שתלו לך שם במרוקו...
> 
> נשלח מה-iPhone שלי
> 
> ב-Mar 27, 2014, בשעה 9:26, Ariel Illouz notifications@github.com כתב/ה:
> 
> > חיובי. למה, הלחצן לא זמין ? 
> >

**Comment by natan1957** [comment]
למעשה כפתור ה אן-דו צריך להיות זמין גם הוא...

**Comment by ariel1974** [comment]
אן-דו?

**Comment by natan1957** [comment]
[image: Inline image 1]

**Comment by ariel1974** [comment]
לא רואים כלום

**Comment by natan1957** [comment]
![image](https://cloud.githubusercontent.com/assets/6491631/2536887/ff8d0dba-b5a6-11e3-9f9c-6545dda733cb.png)

**Comment by ariel1974** [comment]
פקד בטל אינו מחזיר מחיקה - בדקתי - אין טעם לאפשר אותו

**Comment by natan1957** [comment]
OK. 

נשלח מה-iPhone שלי

ב-Mar 28, 2014, בשעה 9:51, Ariel Illouz notifications@github.com כתב/ה:
