### ISSUE TITLE
פתיחת קובץ ללא סאונד והודעות אזהרה

### ISSUE THREAD

**Issue by natan1957** [ariel1974/mymentor#78]
בפתיחת קליפ ללא קובץ סאונד, קובץ הסאונד שהיה טעון קודם, מהקליפ הקודם נשאר במקום להסתלק.

יש לעשות סדר בהודעות אזהרה בזמן פתיחת קובץ על קיום קובץ שטרם נשמר.
לדוגמה, בלחיצה על חדש קופצת אזהרה. אחרי שעונים כן ופותחים אחר ההודעה קופצת שוב.

לעומת זאת בהבאת טקסט מהמאגר, אין בדיקה ואין אזהרה.

**Comment by ariel1974** [comment]
הבא טקסט מהאגר היא פעולה מכוונת על הקליפ שלך. איזו אזהרה אתה מצפה לקבל ?

**Comment by natan1957** [comment]
אם קיים טקסט בחלון הטקסט, יש להזהיר כי הוא הולך להידרס
זה בדיוק כמו פתיחת קובץ על קובץ קיים.

**Comment by ariel1974** [comment]
באיזה שלב ? איזו הודעה ?

2014-03-27 8:29 GMT+02:00 natan1957 notifications@github.com:

**Comment by natan1957** [comment]
בהבאת טקסט מהמאגר, הודעת אזהרה על דריסת הטקסט הקיים צריכה להופיע רק אם יש טקסט קיים.
כרגע היא מופיעה גם מיד לאחר הפעלת היישום כשעדין אין בו כלום
