### ISSUE TITLE
התחברות

### ISSUE THREAD

**Issue by natan1957** [ariel1974/mymentor#79]
אחרי התקנת גרסה המערכת דורשת התחברות וסיסמה.
כנראה בגלל שההתקנה מוחקת את העוגייה. האם זה חובה?

מקש אנטר צריך לפעול כמו מקש המשך...

**Comment by ariel1974** [comment]
חובה...

**Comment by natan1957** [comment]
כן המפקד.

**Comment by natan1957** [comment]
האם אנטר יכול לשמש מקש המשך?

**Comment by ariel1974** [comment]
tupal
