### ISSUE TITLE
שמות שדות קטגוריה של עולמות שונים

### ISSUE THREAD

**Issue by natan1957** [ariel1974/mymentor#81]
לא ברור לי איפה השמות נשמרים, חשבתי שהם צריכים להישמר בטבלת עולמות אבל אני לא רואה אותם שם.
לא בדקתי מה קורה בסטודיו כשאני מפעיל אותו תחת עולם אחר, אבל שמות הקטגוריות צריכים להיות מותאמים לעולם הרלוונטי. לכן הקטגוריות בטבלה נקראים קטגוריה1,2,3 וכו' ולא ראשי, קריאה וכו' שזה שמות של עולם התורה.
האם יש לכך התייחסות?

**Comment by natan1957** [comment]
הוספתי את השמות בטבלת העולמות.
יש להציג אותם משם.

**Comment by ariel1974** [comment]
![image](https://cloud.githubusercontent.com/assets/3278964/2672749/93b78bf2-c0ea-11e3-8a09-1dd540b8ad9d.png)

**Comment by ariel1974** [comment]
טבלת CategoryLabels
לא ממה שהוספת - מחק את זה שלא יהיה בלבול

**Comment by natan1957** [comment]
או קי, לא שמתי לב שזה קיים, אבל לפני שאני מוחק, האם לא נכון יותר להשתמש בטבלת העולמות?
מה היתרון בטבלה נוספת ?

**Comment by natan1957** [comment]
נא תשובתך

**Comment by ariel1974** [comment]
אני חושב שכדאי להפריד את זה, מחר יהיו לך יותר קטגוריות ויותר שפות זה נראה לי יותר מסודר. מעבר לזה אני לא רואה יתרון נוסף

**Comment by natan1957** [comment]
אם כך, לא ברור לי התהליך, לפני שאתה (ותום וירון) טוען את שמות הקטגוריות,
אתה בודק באיזה עולם תוכן נמצא המשתמש ולפי העולם ולפי השפה אתה אמור לגשת
לרשומת השמות.
אבל אין מפתח גישה. להפך... יש מפתח גישה מרשומת שמות לעולם תוכן. לא ברור מתי
משתמשים בו...

2014-04-15 20:27 GMT+03:00 Ariel Illouz notifications@github.com:

**Comment by ariel1974** [comment]
i have user's contentType, and i have local (he-il / en-us) 
that's how i retrieve from CategoryLabels

**Comment by natan1957** [comment]
זה ברור..
זו גישה אס-קיו-אל קלסית.
אז מה התפקיד של הפוינטר לכוון טבלת העולמות, הרי כיוון החיפוש הוא הפוך...

**Comment by ariel1974** [comment]
שוב ולאט...החיתוך של טבלת הלייבלים מתבצעת לפי שני השדות
שפה + קוד עולם תוכן
כשאתה אומר פוינטר - מבחינתי זה פורין-קי
Foreign - Key
ועליו אני מפלטר את הנתונים
