### ISSUE TITLE
יצירת שם שיעור ומקור

### ISSUE THREAD

**Issue by natan1957** [ariel1974/mymentor#82]
לא ברור לי מאפה לקחת את שמות השדות למנגנון השרשור.
איך נקרא הערה באנגלית, איך נקרא שם מורה באנגלית וכו.
בינתיים אני לא מסתדר עם זה.

**Comment by ariel1974** [comment]
יש לך מספר שדות שעטופים בסוגריים להחלפה בהתאמה לפי השפה
[category1], [category2],[category3],[category4],[description],[remarks],[firstName],[lastName],[cityOfResidence]

**Comment by natan1957** [comment]
זאת אומרת שלדוגמה השדה 
remarks
מקבל את הערך העברי או האנגלי בהתאם לשרשור העברי או האנגלי ...

**Comment by natan1957** [comment]
ישנה התנהגות לא ברורה
ערכתי את המחרוזת כמיטב יכולתי
אפשר לראות שהתוספת האנגלית לא מתווספת, חסר פסיק אחרי קטגוריה3, שם המורה צריך להיות מוצג באנגלית
לא ברור מאיזה שדה בטבלה נלקח שם עיר המגורים.
 בנוסף לכך, כאשר אני בוחר קטגוריה1 וקטגוריה2 כלום לא קורה בשם הקליפ. אבל אחרי בחירת קטגוריה3 מוצגים הקטגוריות 1 2 ואילו קטגוריה 3 לא...

![image](https://cloud.githubusercontent.com/assets/6491631/2673340/25bfb41e-c0f2-11e3-919f-f578163fd46b.png)

![image](https://cloud.githubusercontent.com/assets/6491631/2673342/36f971de-c0f2-11e3-80d0-e7b09edd2b1e.png)

**Comment by ariel1974** [comment]
זה תוקן בגרסה האחרונה. אתה בטוח שזה לא תקין אצלך והשם משתמש שלך מכיל עברית
בשדה האנגלית ?

**Comment by ariel1974** [comment]
![image](https://cloud.githubusercontent.com/assets/3278964/2676396/8239e170-c137-11e3-9b5e-ffd4c37dc3f7.png)

**Comment by ariel1974** [comment]
צריך לסדר את הטבלה, אין ערכים באנגלית בכלל

**Comment by ariel1974** [comment]
אני לא מבין, ערכת את שדה
clipSourcePattern כדי לשנות את התנהגות השם ?

**Comment by ariel1974** [comment]
![image](https://cloud.githubusercontent.com/assets/3278964/2676424/6ccc36e8-c138-11e3-9b1f-e38dcbf6ed84.png)

**Comment by natan1957** [comment]
איפה ה rr משדה ה name 
addition ?
איפה ה rr משדה ה name 
addition ? למה הוא לא מופיע בשם?
מאיפה צץ השם האנגלי? אתה הוספת? כי אני כמעט בטוח שהשם האנגלי שלי כלל אנגלית. אחרת... יצאתי פיטה...

נשלח מה-iPhone שלי

ב-Apr 11, 2014, בשעה 8:16, Ariel Illouz notifications@github.com כתב/ה:

**Comment by ariel1974** [comment]
אני הוספתי לשם שלך אנגלית לא היה כלום בכל השמות. פיתה אינדיד.

**Comment by natan1957** [comment]
מה עם ה rr (שואלת הפיטה את הלאפה...)

נשלח מה-iPhone שלי

ב-Apr 11, 2014, בשעה 10:33, Ariel Illouz notifications@github.com כתב/ה:

> אני הוספתי לשם שלך אנגלית לא היה כלום בכל השמות. פיתה אינדיד.

**Comment by ariel1974** [comment]
חח..איזה RR ?

**Comment by natan1957** [comment]
שים לב,
בתמונה שאתה שלחת בשדה Name addition יש תוכן rr.
התוכן הזה צריך להופיע ולהשתרשר בתוך שם השיעוררררררררר.

2014-04-11 11:58 GMT+03:00 Ariel Illouz notifications@github.com:

> חח..איזה RR ?

**Comment by natan1957** [comment]
שים לב לרצף האירועים
![image](https://cloud.githubusercontent.com/assets/6491631/2678707/a3081d3a-c165-11e3-9fe4-7e815857bd4c.png)
![image](https://cloud.githubusercontent.com/assets/6491631/2678720/c295ae06-c165-11e3-97b2-1d1e38947746.png)
![image](https://cloud.githubusercontent.com/assets/6491631/2678732/e0403336-c165-11e3-80d0-f0d8d2880c3e.png)
![image](https://cloud.githubusercontent.com/assets/6491631/2678750/2b470d3c-c166-11e3-80f1-1954b5c3bae5.png)
![image](https://cloud.githubusercontent.com/assets/6491631/2678779/b2dfb640-c166-11e3-841d-23b51d769161.png)

**Comment by natan1957** [comment]
הוספתי את השדות 
CityOfResidence   CityOfResidence_en_us.
משדות אלה יש לקחת את התוכן כדי לשרשר לשם השיעור.
בדוק שיש פסיקים בין הפרמטרים. במיוחד בממשק האנגלי אני חושב שחסר

**Comment by natan1957** [comment]
זה לא עובד עדיין.
ברשומה שלי יש הרצליה וגם באנגלית אבל זה לא מתווסף לשם השיעור

**Comment by ariel1974** [comment]
תנסה לערוך משהו שהוא יקח את זה מחדש

**Comment by natan1957** [comment]
לא מבין...

נשלח מה-iPhone שלי

ב-Apr 16, 2014, בשעה 0:06, Ariel Illouz notifications@github.com כתב/ה:

> תנסה לערוך משהו שהוא יקח את זה מחדש

**Comment by ariel1974** [comment]
תפבלש מחדש ותראה את השם באנגלית בparse.com

**Comment by natan1957** [comment]
אריאל, אני לא צעיר... דבר איתי בעדינותתת
הוספתי את השדות ב
parse.
אכלסתי בשם הישוב.
במסך פרסום, כאשר אני בוחר קטגוריות ושם השיעור נבנה, אני צריך לראות גם את גר בהרצליה כמו שאני רואה מורה נתן הלפמן...
ואני לא רואה את זה... לא באנגלית ולא בעברית.
מה אני עושה לא נכון.
תפרגן לי עוד כמה מילים... לא יתר מידי...

**Comment by natan1957** [comment]
טוב. סוף סוף עובד...
אבל יש לי שאלה:
למה גר ב מופיע מיד עם הצגת המסך, עוד לפני הוספת קטגוריות, ואילו המורה  מופיע רק אחרי בחירת נוסח... 
 זה לא אסון אבל זה יוצר תחושת בלגן ומקריות...
מבחינתי ניתן להוסיף את שני השדות יחד אחרי השלמת שדות החובה ...
