### ISSUE TITLE
שאלות מוולטר

### ISSUE THREAD

**Issue by natan1957** [ariel1974/mymentor#83]
מה תפקיד השדות 
demo size , clip size
ברשומת הקליפ

למה קובץ הסאונד המקוצר לדמו מראה אורך מלא ועוצר באמצע. למה הוא לא מראה את האורך האמיתי?

**Comment by ariel1974** [comment]
אני לא מבין מה הוא רוצה - שיתקשר אלי 
חבל על הטלפון השבור הזה
