### ISSUE TITLE
שמות שדות

### ISSUE THREAD

**Issue by natan1957** [ariel1974/mymentor#85]
יש לשנות את שמות השדות בממשק האנגלי במסך הפרסום ל
name extension
English name extension
![image](https://cloud.githubusercontent.com/assets/6491631/2709533/28e559b4-c4b7-11e3-9d7d-667bf90dc150.png)

וגם ל
description
English description
![image](https://cloud.githubusercontent.com/assets/6491631/2709559/89485dce-c4b7-11e3-8ebb-2ae70df494e1.png)

יש להחליט האם שמות השדות מתחילים עם אותיות גדולות או קטנות.
כמובן ששמות שמתחילים עם מילים כמו 
English
יתחילו עם אות גדולה

**Comment by natan1957** [comment]
כבר רשמתי לך בעבר, ששם השיעור לא מתחולל מיד עם הוספת הקטגוריה אלא באופן מוזר.
כאשר בוחרים ראשי ופרשה לא קורה כלום.
כאשר בוחרים קריאה, מתווספים לשם ראשי ופרשה אבל לא הקריאה.
הקריאה מתווספת רק לאחר בחירת הנוסח...
נכון שאלה שדות חובה ובסוף הכל נכנס, אבל ההתנהגות מבלבלת את המשתמש.
האם ניתן לדאוג לכך שברגע שבוחרים קטגוריה, היא מתווספת מיד ?

**Comment by ariel1974** [comment]
tupal
