### ISSUE TITLE
שינוי פונט בדרך לקובץ ה HTML

### ISSUE THREAD

**Issue by natan1957** [ariel1974/mymentor#87]
קליפ JpNRwRHt96

![image](https://cloud.githubusercontent.com/assets/6491631/2723649/24f4ee38-c597-11e3-9a8a-9050d145c040.png)

**Comment by natan1957** [comment]
בדקתי שמירת פונטים על ידי פרסום מקור עם פונטים מעורבים.
אפילו דחפתי פנימה אובייקט גרפי .
כשאחזרתי את המקור חזר אלי לסטודיו הטקסט עם הפונטים המקוריים כפי ששמרתי.
אני מניח מזה שהטקסט נשמר ב 
HTML
הצורה נכונה. אבל כשאני פותח את הקובץ אני רואה פונט אחיד.
כך שלא ברור לי מה קורה.

**Comment by ariel1974** [comment]
שוב...מתי זה עובד ומתי לא, תהיה יותר ספציפי - מה ז״א ״כשאני פותח את הקובץ״
- איפה ?

2014-04-20 12:00 GMT+03:00 natan1957 notifications@github.com:

**Comment by natan1957** [comment]
חפש בעזרת הסטודיו מקור מסוג הפטרה, תמצא מקור עם תאריך של היום.
אחזר אותו ותראה טקסט עם פונט מעורב.
זה טקסט שאני העליתי לשם בדיקת עניין שמירת הפונטים, וככל שמדובר בשמירת מקור
ואחזור מקור זה מוכיח שהמערכת שומרת את הפונטים כראוי.
אני יוצא מנקודת הנחה שכאשר שמרתי אותו הטקסט נשמר כקובץ HTML.
משום מה כשאני ניגש ל PARSE ופותח את ה HTML אני לא רואה את הפונטים המעורבים
אלא פונט אחיד.
כך שאינני מבין איפה הטעות שלי.,
ומה שהכי חשוב זה שפונט מעורב יישמר גם לשעורים ולא יידרס לפונט אחיד.

2014-04-20 12:08 GMT+03:00 Ariel Illouz notifications@github.com:
