### ISSUE TITLE
שיבוץ עוגנים וחלוקה למילים

### ISSUE THREAD

**Issue by natan1957** [ariel1974/mymentor#89]
חלוקה למילים לפי רווח לא עובדת (עבדה פעם) אבל עכשיו לא.
אני מבקש לקבוע עוגן אחרי ם (מם סופית). הוא מכניס עוגנים גם אחרי מ לא סופית.
במקרה של ניקוד, העוגן נכנס בין האות לניקוד במקום אחרי הניקוד.
אין התייחסות לתו+רווח . אם אני מקיש ה+רווח כדי לתאר סוף מילה שמסתיימת בתו ה, הוא לא מציב עוגנים בכלל.
אם אקיש רק ה, הוא יציב עוגנים גם באמצע מילים. לכן נדרשת האפשרות להקיש רצף.
![image](https://cloud.githubusercontent.com/assets/6491631/2811393/9ec4a598-ce19-11e3-8a52-08add1df5641.png)

**Comment by ariel1974** [comment]
טופל

**Comment by natan1957** [comment]
הועבר לסעיף 121
