### ISSUE TITLE
התייחסות לסטטוס פרסום של המורה ולסטטוס קליפ קיים

### ISSUE THREAD

**Issue by natan1957** [ariel1974/mymentor#90]
הכללים הרשומים כאן נמצאים בטבלה בקובץ האפיון.
למורה יש  סטטוס פרסום
UserPublishingStatus
כרגע יכולים להיות בו שלושה סטטוסים: חסום, טעון בדיקה ופעיל.
,אם סטטוס המורה חסום , אין לאפשר פרסום. יש לתת הודעה על הסטטוס ולהפנות למערכת.
 אם סטטוס המורה טעון בדיקה וקליפ חדש, הקליפ יכול לעלות בסטטוס  בבדיקת מורה או בבדיקת מערכת
אם סטטוס המורה פעיל וקליפ חדש, הוא יכול להעלות בסטטוס מוקפא ע"י מורה בבדיקת מורה או פעיל.

אם הקליפ קיים ומתבצע פרסום מחדש לשם עדכון אז:
אם סטטוס הקליפ נדחה או חסום אין לאפשר פרסום. יש להציג הודעה ולהפנות את המשתמש למערכת.
אם סטטוס המורה טעון בדיקה, וסטטוס הקליפ בבדיקת מערכת או מוקפא מורה, הוא יכול להשאיר או להחליף בניהם.
אם סטטוס הפרסום של המורה פעיל, הוא יכול להעביר בין בדיקת מורה, מוקפא מורה ופעיל.

**Comment by ariel1974** [comment]
למיטב זכרוני זה לא היה באפיון המקורי, זה שינוי/תוספת - למה אתה פותח את זה
כבאג ?

2014-04-27 18:15 GMT+03:00 natan1957 notifications@github.com:

**Comment by natan1957** [comment]
זה נמצא באפיון המקורי, ההתייחסות לכך שסטטוס השיעור מתייחס לסטטוס העלאת
שיעור של המורה. זו אמירה כללית...
מיד לאחר מכן הוספתי טבלה שעושה סדר ומפרטת את האפשרויות.
זו לא תכולה נוספת, אז זה באג... לא במובן של תקלה... אלא במובן של
פונקציונליות שחסרה.

2014-04-27 18:21 GMT+03:00 Ariel Illouz notifications@github.com:

**Comment by natan1957** [comment]
יש חדש עם זה?

**Comment by natan1957** [comment]
מטופל בנושא 152
