### ISSUE TITLE
הוספת קטע סאונד

### ISSUE THREAD

**Issue by natan1957** [ariel1974/mymentor#92]
הוספת קטע סאונד בין שני מעברים, משבשת את התזמונים של המעברים שבהמשך

**Comment by ariel1974** [comment]
תכין לי דוגמא משהו, צעדים לשחזור

2014-05-04 11:54 GMT+03:00 natan1957 notifications@github.com:

**Comment by natan1957** [comment]
זה קורה תמיד. אני מעתיק קטע ומדביק אותו בין מעברים. זה לא דוחף אותם בהתאם...

נשלח מה-iPhone שלי

ב-May 4, 2014, בשעה 14:09, Ariel Illouz notifications@github.com כתב/ה:
