### ISSUE TITLE
מחיקת סאונד עם מעבר

### ISSUE THREAD

**Issue by natan1957** [ariel1974/mymentor#93]
משבשת את התזמונים שבהמשך

**Comment by ariel1974** [comment]
פרט נמק הסבר
תן לי הוראות איך לשחזר את זה

**Comment by natan1957** [comment]
אם אני מוחק את הבחירה המסומנת המעברים לא מתעדכנים ולא נשארים במקום שהם צריכים להישאר
לפני המחיקה
![image](https://cloud.githubusercontent.com/assets/6491631/2873883/667e7ce4-d3c4-11e3-9b4f-5abc2d998658.png)
אחרי המחיקה
![image](https://cloud.githubusercontent.com/assets/6491631/2873892/ae072e62-d3c4-11e3-8f9f-58c746d1ff7b.png)

**Comment by natan1957** [comment]
לפני מחיקה
![image](https://cloud.githubusercontent.com/assets/6491631/2890225/3302ea76-d527-11e3-878e-4ac4ccf757f5.png)

אחרי מחיקה
![image](https://cloud.githubusercontent.com/assets/6491631/2890256/8d5dd5da-d527-11e3-82b3-1d5c8da47a3f.png)

**Comment by ariel1974** [comment]
לא פירטת מה הבעיה כאן

**Comment by natan1957** [comment]
![image](https://cloud.githubusercontent.com/assets/6491631/2890641/a54c6d0c-d52a-11e3-93e4-997e08cfa492.png)

**Comment by ariel1974** [comment]
שלח לי את הקובץ הזה שאבדוק עליו
