### ISSUE TITLE
הדגשת קטע ראשון

### ISSUE THREAD

**Issue by natan1957** [ariel1974/mymentor#96]
כאשר אני משמיע קליפ מתוזמן, קטע הטקסט הראשון לא מודגש אלא רק מהשני.
בדוק את זה בהפטרת שגב מקוצר

**Comment by ariel1974** [comment]
לא משתחזר לי

![image](https://cloud.githubusercontent.com/assets/3278964/2893144/519a7fd0-d545-11e3-9955-df8f7307314f.png)
