### ISSUE TITLE
ניגון וסימון

### ISSUE THREAD

**Issue by natan1957** [ariel1974/mymentor#97]
כאשר אני מסמן בחירת סאונד ומנגן את הבחירה, הניגון עוצר בסוף הסימון והסמן נעמד על ההתחלה (זה טוב)
אבל בניגון פעם שנייה, הניגון ממשיך והסמן יוצא מאזור הבחירה.
אז, אפשר לסמן עוד בחירה, ועוד אחת ועוד אחת...
הקלקה מחוץ לבחירה צריכה לבטל אותה.
![image](https://cloud.githubusercontent.com/assets/6491631/2935806/97231162-d82d-11e3-95ad-c407fe90d451.png)

כאשר ישנה בחירה(מהסוג הצבוע), זום לבחירה צריך לעבוד והוא לא.
כפתור "להתחלה" צריך להחזיר את הסמן לתחילת בחירה (כאשר ישנה בחירה) ולא לתחילת הקובץ. 

קונטרול וי בסאונד עדיין מכניס בסוף הקובץ. צריך להכניס במיקום הסמן.

הוספת אלט לקונטרול בסאונד זה ממש בעייתי למורה המסכן

כשאני מזיז עם העכבר או עם הלחצנים את המעבר הלפני האחרון, המעבר האחרון זז איתו כאילו דבוקים...

**Comment by ariel1974** [comment]
בקשר לאלט - מה אתה רוצה שאעשה, זו מגבלה של הכלי פיתוח אין מעקף
כשאתה מזיז את המעבר האחרון - הוא מניח שאתה משנה רק את זמן ההתחלה ולא את האורך של הקטע

**Comment by natan1957** [comment]
כאשר ישנה בחירה(מהסוג הצבוע), זום לבחירה צריך לעבוד והוא לא.
כפתור "להתחלה" צריך להחזיר את הסמן לתחילת בחירה (כאשר ישנה בחירה) ולא לתחילת הקובץ.

קונטרול וי בסאונד עדיין מכניס בסוף הקובץ. צריך להכניס במיקום הסמן.

הוספת אלט לקונטרול בסאונד זה ממש בעייתי למורה המסכן

כשאני מזיז עם העכבר או עם הלחצנים את המעבר הלפני האחרון, המעבר האחרון זז איתו כאילו דבוקים...
לא הבנתי את התשובה.

**Comment by ariel1974** [comment]
שוב - המעבר האחרון הוא האורך של הקטע האחרון - הוא לא עוגן

**Comment by natan1957** [comment]
כאשר ישנה בחירה(מהסוג הצבוע), זום לבחירה צריך לעבוד והוא לא.
כפתור "להתחלה" צריך להחזיר את הסמן לתחילת בחירה (כאשר ישנה בחירה) ולא לתחילת הקובץ.

קונטרול וי בסאונד עדיין מכניס בסוף הקובץ. צריך להכניס במיקום הסמן.

תזכיר לי, האם ביטלת את עניים ה אלט קונטרול בעריכת סאונד

**Comment by ariel1974** [comment]
, זו דרישה חדשה - לא באג. הקטע הצבוע זו בחירה אחרת ואתה מכיר את הסיבות ליצירתה. מדובר בשעתיים פיתוח, תאשר לי שאמשיך
והסרתי לך את האלט קונטרול בגרסה קודמת - פעילות הקיצורים עכשיו מותנית באיזה טאב אתה נמצא

**Comment by natan1957** [comment]
קיימם חוסר אחידות ובלבול בין  "בחירה" ל"צביעה".
כאשר אני מקליק על עוגן, סביבת המעבר נצבעת.
כאשר אני מקליק על קטע טקסט אזור הסאונד נבחר.
כאשר אני מקליק על מעבר העוגן נבחר וסביבת המעבר נצבעת
כאשר אני מקליק וגורר את העכבר מתבצעת בחירה...
הצביעה נועדה לאפשר הזזת מעבר האזור שהוא מסומן. סימון מסוג בחירה לא אפשר את זה. תזכיר לי אם יש לזה עוד שימוש.
כדי לייצר אחידות אני מבקש הוא לגרום לכך שבכל פעולה שמייצרת בחירה, להחליף מיד את הבחירה מיד בצביעה ולהתייחס לצביעה .
כלבחירה.
, זאת אומרת, בזום, בקופי ודל, בניגוןבהקלקה מחוץ לצביעה וכו
אם זה מסובך או מסוכן, אז אולי צריך לבטל את פתרון הצביעה (אם זה אכן התפקיד היחיד של הצביעה) ולתת פתרון להזזת המעבר שמתחת בחירה.
אולי לחיצה על קונטרול מסלקת את הבחירה, מאפשרת הזזת הסמן ע"י העכבר ושחרור הקונטרול מחזיר את הבחירה סביב המיקום החדש, כמו שקורה עכשיו עם הצביעה
אולי קליק ימני יאפשר לתפוס את המעבר מתחת לבחירה...... 
מה דעתך, תן עיצה...

**Comment by ariel1974** [comment]
יש לי בעית קשב וריכוז. בוא נבדוק את זה עם TeamViewer 
מחר בערב

**Comment by natan1957** [comment]
הועבר לסעיף 118
