### ISSUE TITLE
מחיקת סאונד עם מעבר

### ISSUE THREAD

**Issue by natan1957** [ariel1974/mymentor#99]
אני מבצע מחיקה ומקבל את ההודעה.
![image](https://cloud.githubusercontent.com/assets/6491631/2935905/2bdefe14-d834-11e3-9b72-61310abf461d.png)

אני מאשר ומקבל את התוצאה הבאה
![image](https://cloud.githubusercontent.com/assets/6491631/2935908/4fa80124-d834-11e3-9fc3-412e4338ad49.png)

**Comment by natan1957** [comment]
במחיקת מעבר לפני אחרון, נמחק גם המעבר האחרון.
זה לא צריך לקרות.

**Comment by ariel1974** [comment]
המעבר האחרון הוא האורך של העוגן האחרון - הוא לא באמת מעבר בפני עצמו

**Comment by natan1957** [comment]
הרעיון שמחיקת קטע סאונד עם מעבר מוחקת את העוגן ההיא ליצור סנכרון מקסימלי בין במעברים לעוגנים.
זאת אומרת, שבאופן תאורטי וגם מעשי אחרי פעולה כזו, בהנחה שהקליפ היה מתוזמן, ניתן לבצע שמירה ופרסום ללא תזמון נוסף או תיקון תזמון.
זה לא מתאפשר, אם מחיקת מעבר אחרון מבטלת את המעבר של סוף השיעור.
לא משנה אם זה ממש מעבר או כאילו מעבר... זה תזמון של סוף ההקלטה, ואם הוא נעלם, יש לתזמן מחדש.
לכן יש לוודא שהוא לא מעלם אלא אם מוחקים את כל התזמונים או אותו ספציפית.

**Comment by ariel1974** [comment]
לא ניתן, זה מסובך לממש. הערך של סוף הקליפ מבוסס על דוריישן של המילה האחרונה, זה השלד של המערכת ועל זה מבוסס הכלץ לא יכול להציג את המעבר האחרון בלי להתבסס על זמן התחלה של המעבר.

**Comment by natan1957** [comment]
למה שלא תבסס את הערך של המעבר האחרון על הדיוריישן(אהבתי..) של כל הקליפ. ז"א המרחק שלו מהמעבר הראשון....
אז גם תיפסק התזוזה שלו כשמזיזים את המעבר האחרון..
